// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {IClaimVerifier} from "../interfaces/IClaimVerifier.sol";
import {IReputation} from "../interfaces/IReputation.sol";

/// @title ClaimVerifier
/// @notice The real `claim` verifier behind the frozen `IClaimVerifier` (PLURISWAP.md §3.15.5,
///         §3.15.9, V3): an ultra_honk proof generated by the pinned toolchain (see
///         circuits/README.md). The proof says "I know the account behind
///         `dealSubject = Poseidon(sk_id, dealId)`; its current leaf sits in a live tree;
///         `newLeaf` is that leaf with the terminal delta (`kind`, `principal`, `token`)
///         applied — §3.15.5's table proven in-circuit, including `inFlight >= principal` —
///         and `nullRep(v)` is the current version's nullifier" — exactly what
///         `PrivateReputation.claim` consumes against the kernel's `pending` record.
/// @dev Fail-closed everywhere: a malformed blob, an arg the proof's public inputs do not
///      name, a failed deploy, or any revert inside the generated verifier reads as `false` —
///      never as a revert-shaped pass (the interface pins this).
///
///      The proof blob is `proof || public_inputs` (bb's layout): the trailing 256 bytes are
///      the eight public inputs in circuit order — `dealId`, `dealSubject`, `newLeaf`,
///      `nullRep`, `kind`, `token`, `principal`, `repRoot`. The first seven must match the
///      interface args exactly — `kind` is the pending record's Close enum (0..5, compared
///      as `uint8`), `token` as the numeric cast (right-aligned field element), `principal`
///      raw — and `repRoot` is the live root the module gated. The delta arithmetic is the
///      circuit's own; the adapter only binds the proof to the record the kernel wrote. The
///      Honk verifier itself is deployed from committed initcode (`test/fixtures/verifiers/`,
///      produced by `bun circuits:prove`) — the main tree cannot compile it (via_ir vs the
///      generated dispatchers; see circuits/README.md) — and is called by address and
///      selector, never linked.
contract ClaimVerifier is IClaimVerifier {
    /// @dev `verify(bytes,bytes32[])` — the generated ultra_honk verifier's only entrypoint.
    bytes4 internal constant VERIFY_SELECTOR = bytes4(keccak256("verify(bytes,bytes32[])"));

    /// @dev (dealId, dealSubject, newLeaf, nullRep, kind, token, principal, repRoot, pairTag, epoch) —
    ///      must mirror claim's pub signature order.
    uint256 internal constant PUBLIC_INPUTS = 10;

    /// @dev The BN254 scalar field — the domain of every public input the circuits prove over.
    uint256 internal constant BN254_P = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    /// @dev The generated Honk verifier, deployed from initcode in the constructor. Zero
    ///      (deploy failed) fails every verify.
    address public immutable honkVerifier;

    constructor(bytes memory verifierInitcode) {
        address deployed;
        assembly {
            deployed := create(0, add(verifierInitcode, 0x20), mload(verifierInitcode))
        }
        honkVerifier = deployed;
    }

    /// @inheritdoc IClaimVerifier
    function verifyClaim(
        bytes32 dealId,
        bytes32 dealSubject,
        bytes32 newLeaf,
        bytes32 nullRep,
        IReputation.Close kind,
        address token,
        uint256 principal,
        bytes32 repRoot,
        bytes32 pairTag,
        uint256 epoch,
        bytes calldata proof
    ) external view returns (bool) {
        if (honkVerifier == address(0)) return false; // deploy failed — fail closed
        // A blob that cannot even carry the public inputs section is malformed: false,
        // never a panic (the empty-pubs path below would be an out-of-bounds read).
        if (proof.length < PUBLIC_INPUTS * 32) return false;
        (bytes32[] memory pubs, bytes calldata honkProof) = _split(proof);
        // `dealId` is a raw bytes32 tag (keccak-derived, may sit over p); the proof names
        // its canonical field element — the pinned mod-p rule, at the adapter boundary.
        if (uint256(pubs[0]) != uint256(dealId) % BN254_P) return false; // the deal the delta belongs to
        if (pubs[1] != dealSubject) return false; // the subject the kernel snapshotted
        if (pubs[2] != newLeaf) return false; // the delta leaf the module will insert
        if (pubs[3] != nullRep) return false; // the version nullifier the module will burn
        if (pubs[4] != bytes32(uint256(uint8(kind)))) return false; // pending's Close, 0..5
        // The numeric cast, not a raw bytes20 cast: the proof's field element is the
        // address as an integer (right-aligned), while bytes32(bytes20) would left-align.
        if (pubs[5] != bytes32(uint256(uint160(token)))) return false; // raw address < p always
        if (pubs[6] != bytes32(principal)) return false; // raw amount; >= p can never match
        if (pubs[7] != repRoot) return false; // the live root the module gated
        // The two §3.14.7 inputs the prover does not choose: the pair tag the module stored when both
        // sides admitted, and the epoch the module read off the chain's own clock. A claim that wants
        // credit for a counterparty it invented, or in a window it picked, cannot name either.
        if (pubs[8] != pairTag) return false;
        if (pubs[9] != bytes32(epoch)) return false;
        return _verify(honkProof, pubs);
    }

    /// @dev Split the blob into the trailing public inputs and the proof body. Malformed
    ///      length returns empty pubs, which fails every caller's checks — never reverts.
    function _split(bytes calldata blob) internal pure returns (bytes32[] memory, bytes calldata) {
        if (blob.length < PUBLIC_INPUTS * 32) {
            return (new bytes32[](0), blob[0:0]);
        }
        uint256 proofLen = blob.length - PUBLIC_INPUTS * 32;
        bytes32[] memory pubs = new bytes32[](PUBLIC_INPUTS);
        for (uint256 i = 0; i < PUBLIC_INPUTS; i++) {
            pubs[i] = bytes32(blob[proofLen + i * 32:proofLen + (i + 1) * 32]);
        }
        return (pubs, blob[0:proofLen]);
    }

    /// @dev Call the generated verifier. `verify` is `view`: staticcall, so the adapter cannot
    ///      even be tricked into a state change; any revert or short/odd return is `false`.
    function _verify(bytes calldata honkProof, bytes32[] memory pubs) internal view returns (bool) {
        (bool ok, bytes memory ret) = honkVerifier.staticcall(abi.encodeWithSelector(VERIFY_SELECTOR, honkProof, pubs));
        return ok && ret.length == 32 && abi.decode(ret, (bool));
    }
}
