// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {IPrepareAdmitVerifier} from "../interfaces/IPrepareAdmitVerifier.sol";

/// @title PrepareAdmitVerifier
/// @notice The real `prepare_admit` verifier behind the frozen `IPrepareAdmitVerifier`
///         (PLURISWAP.md §3.15.9, V2): an ultra_honk proof generated by the pinned toolchain
///         (see circuits/README.md). The proof says "I know the account behind `dealSubject`;
///         its current leaf holds `inFlight + principal <= cap` with the §3.14.7 tier computed
///         IN-CIRCUIT from the leaf's own stats; `newLeaf` is that leaf with the principal
///         taken into flight; `nullRep(v)` is the old version's nullifier" — exactly what
///         `PrivateReputation.prepare` consumes.
/// @dev Fail-closed everywhere: a malformed blob, an arg the proof's public inputs do not
///      name, a failed deploy, or any revert inside the generated verifier reads as `false` —
///      never as a revert-shaped pass (the interface pins this).
///
///      The proof blob is `proof || public_inputs` (bb's layout): the trailing 256 bytes are
///      the eight public inputs in circuit order — `dealSubject`, `newLeaf`, `nullRep`,
///      `token`, `principal`, `lockCommit`, `repRoot`, `decimals`. The first seven must
///      match the interface args exactly; the eighth is the amplification the frozen
///      interface has no field for: the tier's scale `UNIT = 250 * 10^decimals` is bound to
///      the SERVED token, so the adapter reads the token's own `decimals()` and requires the
///      proof to have used it — a proof scaled for another token's decimals cannot admit
///      this deal (the tier caps are per-token integers, §3.14.7).
///
///      Two more amplifications the circuit cannot do alone:
///      * `lockCommit` must be ZERO in V2 — the interface pins it ("zero without bonds";
///        the private vault arrives in F3). The circuit's bond column (the higher caps of
///        §3.14.7) is selected by `lockCommit != 0`; without a vault to cross-check the lock
///        against, a non-zero lockCommit would buy the bond column for free.
///      * `token` is compared as the plain address (< p always, so raw equality is sound),
///        and `principal` likewise raw: an amount at or over p can never equal the proof's
///        field element — fail-closed by construction.
///      The Honk verifier itself is deployed from committed initcode (`test/fixtures/
///      verifiers/`, produced by `bun circuits:prove`) — the main tree cannot compile it
///      (via_ir vs the generated dispatchers; see circuits/README.md) — and is called by
///      address and selector, never linked.
contract PrepareAdmitVerifier is IPrepareAdmitVerifier {
    /// @dev `verify(bytes,bytes32[])` — the generated ultra_honk verifier's only entrypoint.
    bytes4 internal constant VERIFY_SELECTOR = bytes4(keccak256("verify(bytes,bytes32[])"));

    /// @dev `decimals()` of the served ERC-20 — the tier scale is the token's own.
    bytes4 internal constant DECIMALS_SELECTOR = bytes4(keccak256("decimals()"));

    /// @dev (subject, newLeaf, nullRep, token, principal, lockCommit, repRoot, decimals) —
    ///      must mirror prepare_admit's pub signature order.
    uint256 internal constant PUBLIC_INPUTS = 8;

    /// @dev The generated Honk verifier, deployed from initcode in the constructor. Zero
    ///      (deploy failed) fails every verify.
    address public immutable honkVerifier;

    constructor(bytes memory verifierInitcode) {
        address deployed;
        assembly {
            deployed := create(0, add(verifierInitcode, 0x20), mload(verifierInitcode))
        }
        honkVerifier = deployed;
    }

    /// @inheritdoc IPrepareAdmitVerifier
    function verifyAdmit(
        bytes32 dealSubject,
        bytes32 newLeaf,
        bytes32 nullRep,
        address token,
        uint256 principal,
        bytes32 lockCommit,
        bytes32 repRoot,
        bytes calldata proof
    ) external view returns (bool) {
        if (honkVerifier == address(0)) return false; // deploy failed — fail closed
        // V2 wiring: no vault exists, so the bond column of the cap table is unreachable —
        // a non-zero lockCommit has nothing behind it (the interface pins zero without bonds).
        if (lockCommit != bytes32(0)) return false;
        // A blob that cannot even carry the public inputs section is malformed: false,
        // never a panic (the empty-pubs path below would be an out-of-bounds read).
        if (proof.length < PUBLIC_INPUTS * 32) return false;
        (bytes32[] memory pubs, bytes calldata honkProof) = _split(proof);
        if (pubs[0] != dealSubject) return false; // the subject the passport also prepared
        if (pubs[1] != newLeaf) return false; // the leaf the module will insert
        if (pubs[2] != nullRep) return false; // the version nullifier the module will burn
        // The numeric cast, not a raw bytes20 cast: the proof's field element is the
        // address as an integer (right-aligned), while bytes32(bytes20) would left-align.
        if (pubs[3] != bytes32(uint256(uint160(token)))) return false; // raw address < p always
        if (pubs[4] != bytes32(principal)) return false; // raw amount; >= p can never match
        if (pubs[5] != lockCommit) return false; // zero here, zero in the proof
        if (pubs[6] != repRoot) return false; // the live root the module gated
        // The tier scale belongs to the served token (§3.14.7: caps in integer token units,
        // UNIT = 250 * 10^decimals): the proof must have used the token's own decimals.
        if (_decimalsOf(token) != uint256(pubs[7])) return false;
        return _verify(honkProof, pubs);
    }

    /// @dev Split the blob into the trailing public inputs and the proof body. Malformed
    ///      length returns empty pubs, which fails every caller's checks — never reverts.
    function _split(bytes calldata blob) internal pure returns (bytes32[] memory, bytes calldata) {
        if (blob.length < PUBLIC_INPUTS * 32) {
            return (new bytes32[](0), blob[0:0]);
        }
        uint256 proofLen = blob.length - PUBLIC_INPUTS * 32;
        bytes32[] memory pubs = new bytes32[](PUBLIC_INPUTS);
        for (uint256 i = 0; i < PUBLIC_INPUTS; i++) {
            pubs[i] = bytes32(blob[proofLen + i * 32:proofLen + (i + 1) * 32]);
        }
        return (pubs, blob[0:proofLen]);
    }

    /// @dev The served token's `decimals()`. Fail-closed read: any revert, missing code or
    ///      short return decodes to a sentinel no proof can name (the circuit bounds decimals
    ///      below 32; the sentinel is far past it).
    function _decimalsOf(address token) internal view returns (uint256) {
        (bool ok, bytes memory ret) = token.staticcall(abi.encodeWithSelector(DECIMALS_SELECTOR));
        if (!ok || ret.length < 32) return type(uint256).max;
        return abi.decode(ret, (uint256));
    }

    /// @dev Call the generated verifier. `verify` is `view`: staticcall, so the adapter cannot
    ///      even be tricked into a state change; any revert or short/odd return is `false`.
    function _verify(bytes calldata honkProof, bytes32[] memory pubs) internal view returns (bool) {
        (bool ok, bytes memory ret) = honkVerifier.staticcall(abi.encodeWithSelector(VERIFY_SELECTOR, honkProof, pubs));
        return ok && ret.length == 32 && abi.decode(ret, (bool));
    }
}
