// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {IPreparePassportVerifier} from "../interfaces/IPreparePassportVerifier.sol";

/// @title PreparePassportVerifier
/// @notice The real `prepare_passport` verifier behind the frozen `IPreparePassportVerifier`
///         (PLURISWAP.md §3.15.9, V2): an ultra_honk proof generated by the pinned toolchain
///         (see circuits/README.md). The proof says "I know the `sk_id` behind `dealSubject`
///         = Poseidon(sk_id, dealId), and its account leaf sits in a live tree" — exactly what
///         `PrivatePassport.prepare` buffers under the wallet-signed deal.
/// @dev Fail-closed everywhere: a malformed blob, a subject or root the interface args do not
///      name, a failed deploy, or any revert inside the generated verifier reads as `false` —
///      never as a revert-shaped pass (the interface pins this).
///
///      The proof blob is `proof || public_inputs` (bb's layout): the trailing 64 bytes are
///      the two public inputs in circuit order — `dealSubject`, `repRoot`. The module has
///      already gated `repRoot` against the account tree's ring buffer (`isKnownRoot`) before
///      this call; the adapter re-checks both pubs against the interface args so the proof
///      and the named deal can never diverge. The Honk verifier itself is deployed from
///      committed initcode (`test/fixtures/verifiers/`, produced by `bun circuits:prove`) —
///      the main tree cannot compile it (via_ir vs the generated dispatchers; see
///      circuits/README.md) — and is called by address and selector, never linked.
contract PreparePassportVerifier is IPreparePassportVerifier {
    /// @dev `verify(bytes,bytes32[])` — the generated ultra_honk verifier's only entrypoint.
    bytes4 internal constant VERIFY_SELECTOR = bytes4(keccak256("verify(bytes,bytes32[])"));

    /// @dev (dealSubject, repRoot) — must mirror prepare_passport's pub signature order.
    uint256 internal constant PUBLIC_INPUTS = 2;

    /// @dev The generated Honk verifier, deployed from initcode in the constructor. Zero
    ///      (deploy failed) fails every verify.
    address public immutable honkVerifier;

    constructor(bytes memory verifierInitcode) {
        address deployed;
        assembly {
            deployed := create(0, add(verifierInitcode, 0x20), mload(verifierInitcode))
        }
        honkVerifier = deployed;
    }

    /// @inheritdoc IPreparePassportVerifier
    function verifyPassport(bytes32 dealSubject, bytes32 repRoot, bytes calldata proof) external view returns (bool) {
        if (honkVerifier == address(0)) return false; // deploy failed — fail closed
        // A blob that cannot even carry the public inputs section is malformed: false,
        // never a panic (the empty-pubs path below would be an out-of-bounds read).
        if (proof.length < PUBLIC_INPUTS * 32) return false;
        (bytes32[] memory pubs, bytes calldata honkProof) = _split(proof);
        if (pubs[0] != dealSubject) return false; // the subject the wallet signed to
        if (pubs[1] != repRoot) return false; // the live root the module gated
        return _verify(honkProof, pubs);
    }

    /// @dev Split the blob into the trailing public inputs and the proof body. Malformed
    ///      length returns empty pubs, which fails every caller's checks — never reverts.
    function _split(bytes calldata blob) internal pure returns (bytes32[] memory, bytes calldata) {
        if (blob.length < PUBLIC_INPUTS * 32) {
            return (new bytes32[](0), blob[0:0]);
        }
        uint256 proofLen = blob.length - PUBLIC_INPUTS * 32;
        bytes32[] memory pubs = new bytes32[](PUBLIC_INPUTS);
        for (uint256 i = 0; i < PUBLIC_INPUTS; i++) {
            pubs[i] = bytes32(blob[proofLen + i * 32:proofLen + (i + 1) * 32]);
        }
        return (pubs, blob[0:proofLen]);
    }

    /// @dev Call the generated verifier. `verify` is `view`: staticcall, so the adapter cannot
    ///      even be tricked into a state change; any revert or short/odd return is `false`.
    function _verify(bytes calldata honkProof, bytes32[] memory pubs) internal view returns (bool) {
        (bool ok, bytes memory ret) = honkVerifier.staticcall(abi.encodeWithSelector(VERIFY_SELECTOR, honkProof, pubs));
        return ok && ret.length == 32 && abi.decode(ret, (bool));
    }
}
