// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {IPrepareBondVerifier} from "../interfaces/IPrepareBondVerifier.sol";

/// @title PrepareBondVerifier
/// @notice The real `prepare_bond` verifier behind the frozen `IPrepareBondVerifier`
///         (PLURISWAP.md §3.15.4 "Bond", §3.15.9, V3): an ultra_honk proof generated by the
///         pinned toolchain (see circuits/README.md). The proof says "I own the note behind
///         `nullBond` (a live leaf of `bondRoot`, a note of the deal's `token` worth
///         `noteAmount`); I split it into `lockCommit` and `changeNote` with
///         `noteAmount >= lockAmount` (the change commits to the exact remainder); and
///         `dealSubject = Poseidon(sk_id, dealId)`" — exactly what `PrivateBondVault.prepare`
///         consumes in the activation bundle.
/// @dev Fail-closed everywhere: a malformed blob, an arg the proof's public inputs do not
///      name, a failed deploy, or any revert inside the generated verifier reads as `false` —
///      never as a revert-shaped pass (the interface pins this).
///
///      The proof blob is `proof || public_inputs` (bb's layout): the trailing 256 bytes are
///      the eight public inputs in circuit order — `dealSubject`, `dealId`, `token`,
///      `lockAmount`, `lockCommit`, `changeNote`, `nullBond`, `bondRoot`. `lockAmount` and
///      `token` are public BY DESIGN (F3's amendment): the vault's `reserve` cross-checks
///      them against §3.14.5 — a hidden amount could under-cover its own lock and leave the
///      vault insolvent the day that lock is slashed. The conservation itself
///      (`noteAmount >= lockAmount`, the change the exact remainder) is proven in-circuit.
///      `token` is compared as the numeric cast (right-aligned field element), `lockAmount`
///      raw: a value at or over p can never match — fail-closed by construction. The Honk
///      verifier itself is deployed from committed initcode (`test/fixtures/verifiers/`,
///      produced by `bun circuits:prove`) — the main tree cannot compile it (via_ir vs the
///      generated dispatchers; see circuits/README.md) — and is called by address and
///      selector, never linked.
contract PrepareBondVerifier is IPrepareBondVerifier {
    /// @dev `verify(bytes,bytes32[])` — the generated ultra_honk verifier's only entrypoint.
    bytes4 internal constant VERIFY_SELECTOR = bytes4(keccak256("verify(bytes,bytes32[])"));

    /// @dev (dealSubject, dealId, token, lockAmount, lockCommit, changeNote, nullBond,
    ///      bondRoot) — must mirror prepare_bond's pub signature order.
    uint256 internal constant PUBLIC_INPUTS = 8;

    /// @dev The BN254 scalar field — the domain of every public input the circuits prove over.
    uint256 internal constant BN254_P = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    /// @dev The generated Honk verifier, deployed from initcode in the constructor. Zero
    ///      (deploy failed) fails every verify.
    address public immutable honkVerifier;

    constructor(bytes memory verifierInitcode) {
        address deployed;
        assembly {
            deployed := create(0, add(verifierInitcode, 0x20), mload(verifierInitcode))
        }
        honkVerifier = deployed;
    }

    /// @inheritdoc IPrepareBondVerifier
    function verifyBond(
        bytes32 dealSubject,
        bytes32 dealId,
        address token,
        uint256 lockAmount,
        bytes32 lockCommit,
        bytes32 changeNote,
        bytes32 nullBond,
        bytes32 bondRoot,
        bytes calldata proof
    ) external view returns (bool) {
        if (honkVerifier == address(0)) return false; // deploy failed — fail closed
        // A blob that cannot even carry the public inputs section is malformed: false,
        // never a panic (the empty-pubs path below would be an out-of-bounds read).
        if (proof.length < PUBLIC_INPUTS * 32) return false;
        (bytes32[] memory pubs, bytes calldata honkProof) = _split(proof);
        if (pubs[0] != dealSubject) return false; // the pseudonym the wallet signed to
        // `dealId` is a raw bytes32 tag (keccak-derived, may sit over p); the proof names
        // its canonical field element — the pinned mod-p rule, at the adapter boundary.
        if (uint256(pubs[1]) != uint256(dealId) % BN254_P) return false;
        // The numeric cast, not a raw bytes20 cast: the proof's field element is the
        // address as an integer (right-aligned), while bytes32(bytes20) would left-align.
        if (pubs[2] != bytes32(uint256(uint160(token)))) return false; // raw address < p always
        if (pubs[3] != bytes32(lockAmount)) return false; // §3.14.5's lock; >= p can never match
        if (pubs[4] != lockCommit) return false; // the earmark reserve will open
        if (pubs[5] != changeNote) return false; // the note the vault will insert
        if (pubs[6] != nullBond) return false; // the nullifier the vault will burn
        if (pubs[7] != bondRoot) return false; // the live root the vault gated
        return _verify(honkProof, pubs);
    }

    /// @dev Split the blob into the trailing public inputs and the proof body. Malformed
    ///      length returns empty pubs, which fails every caller's checks — never reverts.
    function _split(bytes calldata blob) internal pure returns (bytes32[] memory, bytes calldata) {
        if (blob.length < PUBLIC_INPUTS * 32) {
            return (new bytes32[](0), blob[0:0]);
        }
        uint256 proofLen = blob.length - PUBLIC_INPUTS * 32;
        bytes32[] memory pubs = new bytes32[](PUBLIC_INPUTS);
        for (uint256 i = 0; i < PUBLIC_INPUTS; i++) {
            pubs[i] = bytes32(blob[proofLen + i * 32:proofLen + (i + 1) * 32]);
        }
        return (pubs, blob[0:proofLen]);
    }

    /// @dev Call the generated verifier. `verify` is `view`: staticcall, so the adapter cannot
    ///      even be tricked into a state change; any revert or short/odd return is `false`.
    function _verify(bytes calldata honkProof, bytes32[] memory pubs) internal view returns (bool) {
        (bool ok, bytes memory ret) = honkVerifier.staticcall(abi.encodeWithSelector(VERIFY_SELECTOR, honkProof, pubs));
        return ok && ret.length == 32 && abi.decode(ret, (bool));
    }
}
