// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {IReabsorbVerifier} from "../interfaces/IReabsorbVerifier.sol";

/// @title ReabsorbVerifier
/// @notice The real `reabsorb` verifier behind the frozen `IReabsorbVerifier` (PLURISWAP.md
///         §3.15.6, §3.15.9, V3): an ultra_honk proof generated by the pinned toolchain (see
///         circuits/README.md). The proof says "I know the account behind
///         `dealSubject = Poseidon(sk_id, dealId)`; the stored `lockCommit` opens to exactly
///         `(sk_id, dealId, amount, salt)`; and `newNote = Poseidon(sk_id, token, amount,
///         newSalt)`" — exactly what `PrivateBondVault.reabsorb` consumes over its own lock
///         record, gated by `reputation.claimed`.
/// @dev Fail-closed everywhere: a malformed blob, an arg the proof's public inputs do not
///      name, a failed deploy, or any revert inside the generated verifier reads as `false` —
///      never as a revert-shaped pass (the interface pins this).
///
///      The proof blob is `proof || public_inputs` (bb's layout): the trailing 224 bytes are
///      the seven public inputs in circuit order — `dealId`, `dealSubject`, `token`, `amount`,
///      `lockCommit`, `newNote`, `nullBond`. `dealId`, `dealSubject`, `lockCommit` and
///      `newNote` come from the caller; `token` and `amount` are read from the vault's own
///      lock record (the caller does not supply them) — the adapter compares them all raw:
///      `token` as the numeric cast (right-aligned field element), `amount` raw so a value at
///      or over p can never match. No root and no membership exist here (the lock record is
///      contract state, not a leaf); the nullifier is one-use-per-lock. The Honk verifier
///      itself is deployed from committed initcode (`test/fixtures/verifiers/`, produced by
///      `bun circuits:prove`) — the main tree cannot compile it (via_ir vs the generated
///      dispatchers; see circuits/README.md) — and is called by address and selector,
///      never linked.
contract ReabsorbVerifier is IReabsorbVerifier {
    /// @dev `verify(bytes,bytes32[])` — the generated ultra_honk verifier's only entrypoint.
    bytes4 internal constant VERIFY_SELECTOR = bytes4(keccak256("verify(bytes,bytes32[])"));

    /// @dev (dealId, dealSubject, token, amount, lockCommit, newNote, nullBond) —
    ///      must mirror reabsorb's pub signature order.
    uint256 internal constant PUBLIC_INPUTS = 7;

    /// @dev The BN254 scalar field — the domain of every public input the circuits prove over.
    uint256 internal constant BN254_P = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    /// @dev The generated Honk verifier, deployed from initcode in the constructor. Zero
    ///      (deploy failed) fails every verify.
    address public immutable honkVerifier;

    constructor(bytes memory verifierInitcode) {
        address deployed;
        assembly {
            deployed := create(0, add(verifierInitcode, 0x20), mload(verifierInitcode))
        }
        honkVerifier = deployed;
    }

    /// @inheritdoc IReabsorbVerifier
    function verifyReabsorb(
        bytes32 dealId,
        bytes32 dealSubject,
        address token,
        uint256 amount,
        bytes32 lockCommit,
        bytes32 newNote,
        bytes32 nullBond,
        bytes calldata proof
    ) external view returns (bool) {
        if (honkVerifier == address(0)) return false; // deploy failed — fail closed
        // A blob that cannot even carry the public inputs section is malformed: false,
        // never a panic (the empty-pubs path below would be an out-of-bounds read).
        if (proof.length < PUBLIC_INPUTS * 32) return false;
        (bytes32[] memory pubs, bytes calldata honkProof) = _split(proof);
        // `dealId` is a raw bytes32 tag (keccak-derived, may sit over p); the proof names
        // its canonical field element — the pinned mod-p rule, at the adapter boundary.
        if (uint256(pubs[0]) != uint256(dealId) % BN254_P) return false; // the deal whose lock this was
        if (pubs[1] != dealSubject) return false; // the account behind the lock
        // The numeric cast, not a raw bytes20 cast: the proof's field element is the
        // address as an integer (right-aligned), while bytes32(bytes20) would left-align.
        if (pubs[2] != bytes32(uint256(uint160(token)))) return false; // raw address < p always
        if (pubs[3] != bytes32(amount)) return false; // the record's amount; >= p never matches
        if (pubs[4] != lockCommit) return false; // the record's earmark, opened by the proof
        if (pubs[5] != newNote) return false; // the note the vault will insert
        if (pubs[6] != nullBond) return false; // the lock nullifier the vault will burn
        return _verify(honkProof, pubs);
    }

    /// @dev Split the blob into the trailing public inputs and the proof body. Malformed
    ///      length returns empty pubs, which fails every caller's checks — never reverts.
    function _split(bytes calldata blob) internal pure returns (bytes32[] memory, bytes calldata) {
        if (blob.length < PUBLIC_INPUTS * 32) {
            return (new bytes32[](0), blob[0:0]);
        }
        uint256 proofLen = blob.length - PUBLIC_INPUTS * 32;
        bytes32[] memory pubs = new bytes32[](PUBLIC_INPUTS);
        for (uint256 i = 0; i < PUBLIC_INPUTS; i++) {
            pubs[i] = bytes32(blob[proofLen + i * 32:proofLen + (i + 1) * 32]);
        }
        return (pubs, blob[0:proofLen]);
    }

    /// @dev Call the generated verifier. `verify` is `view`: staticcall, so the adapter cannot
    ///      even be tricked into a state change; any revert or short/odd return is `false`.
    function _verify(bytes calldata honkProof, bytes32[] memory pubs) internal view returns (bool) {
        (bool ok, bytes memory ret) = honkVerifier.staticcall(abi.encodeWithSelector(VERIFY_SELECTOR, honkProof, pubs));
        return ok && ret.length == 32 && abi.decode(ret, (bool));
    }
}
