// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {IHumanityVerifier} from "../interfaces/IHumanityVerifier.sol";
import {HumanityRegistry} from "../HumanityRegistry.sol";

/// @title RegistryHumanityVerifier
/// @notice The real `register_humanity` verifier behind the frozen `IHumanityVerifier`
///         (PLURISWAP.md §3.15.9, V1): an ultra_honk proof generated by the pinned toolchain
///         (see circuits/README.md), checked against the served `HumanityRegistry`.
/// @dev Fail-closed everywhere: a malformed blob, a wrong root, a foreign registry domain,
///      a failed deploy, or any revert inside the generated verifier reads as `false` —
///      never as a revert-shaped pass (the interface pins this).
///
///      The proof blob is `proof || public_inputs` (bb's layout): the trailing 96 bytes are
///      the three public inputs in circuit order — `hn`, `root`, `registryId`. The adapter
///      SPLITS the blob and amplifies the check the circuit cannot do on-chain:
///      the root must be live in the registry's ring buffer, and the domain must be the
///      served registry's. The Honk verifier itself is deployed from committed initcode
///      (`test/fixtures/verifiers/`, produced by `bun circuits:prove`) — the main tree cannot
///      compile it (via_ir vs the generated dispatchers; see circuits/README.md) — and is
///      called by address and selector, never linked.
contract RegistryHumanityVerifier is IHumanityVerifier {
    /// @dev `verify(bytes,bytes32[])` — the generated ultra_honk verifier's only entrypoint.
    bytes4 internal constant VERIFY_SELECTOR = bytes4(keccak256("verify(bytes,bytes32[])"));

    /// @dev The BN254 scalar field — the domain of every public input the circuits prove over.
    uint256 internal constant BN254_P = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    /// @dev (hn, root, registryId) — must mirror register_humanity's pub signature order.
    uint256 internal constant PUBLIC_INPUTS = 3;

    HumanityRegistry public immutable registry;
    /// @dev The generated Honk verifier, deployed from initcode in the constructor. Zero
    ///      (deploy failed) fails every verify.
    address public immutable honkVerifier;

    error ZeroRegistry();

    constructor(HumanityRegistry registry_, bytes memory verifierInitcode) {
        if (address(registry_) == address(0)) revert ZeroRegistry();
        registry = registry_;
        address deployed;
        assembly {
            deployed := create(0, add(verifierInitcode, 0x20), mload(verifierInitcode))
        }
        honkVerifier = deployed;
    }

    /// @inheritdoc IHumanityVerifier
    function verifyHumanity(bytes calldata proof, bytes32 hn) external view returns (bool) {
        if (honkVerifier == address(0)) return false; // deploy failed — fail closed
        // A blob that cannot even carry the public inputs section is malformed: false, never
        // a panic (the empty-pubs path below would be an out-of-bounds read).
        if (proof.length < PUBLIC_INPUTS * 32) return false;
        (bytes32[] memory pubs, bytes calldata honkProof) = _split(proof);
        if (pubs[0] != hn) return false; // the nullifier the passport is about to burn
        if (!registry.isKnownRoot(pubs[1])) return false; // the enrollment root must be live
        // The registry domain is a raw bytes32 tag (keccak-derived, may sit over p); the
        // proof names its canonical field element. The pinned mod-p rule applies here,
        // at the adapter boundary — a pub input can never be >= p and still match.
        if (uint256(pubs[2]) != uint256(registry.registryId()) % BN254_P) return false;
        return _verify(honkProof, pubs);
    }

    /// @dev Split the blob into the trailing public inputs and the proof body. Malformed
    ///      length returns empty pubs, which fails every caller's checks — never reverts.
    function _split(bytes calldata blob) internal pure returns (bytes32[] memory, bytes calldata) {
        if (blob.length < PUBLIC_INPUTS * 32) {
            return (new bytes32[](0), blob[0:0]);
        }
        uint256 proofLen = blob.length - PUBLIC_INPUTS * 32;
        bytes32[] memory pubs = new bytes32[](PUBLIC_INPUTS);
        for (uint256 i = 0; i < PUBLIC_INPUTS; i++) {
            pubs[i] = bytes32(blob[proofLen + i * 32:proofLen + (i + 1) * 32]);
        }
        return (pubs, blob[0:proofLen]);
    }

    /// @dev Call the generated verifier. `verify` is `view`: staticcall, so the adapter cannot
    ///      even be tricked into a state change; any revert or short/odd return is `false`.
    function _verify(bytes calldata honkProof, bytes32[] memory pubs) internal view returns (bool) {
        (bool ok, bytes memory ret) = honkVerifier.staticcall(abi.encodeWithSelector(VERIFY_SELECTOR, honkProof, pubs));
        return ok && ret.length == 32 && abi.decode(ret, (bool));
    }
}
