// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {IWithdrawVerifier} from "../interfaces/IWithdrawVerifier.sol";

/// @title WithdrawVerifier
/// @notice The real `withdraw` verifier behind the frozen `IWithdrawVerifier` (PLURISWAP.md
///         §3.15.6, §3.15.9, V3): an ultra_honk proof generated by the pinned toolchain (see
///         circuits/README.md). The proof says "I own the note behind `nullBond` (a live leaf
///         of `bondRoot`, a note of the public `token` worth `noteAmount`);
///         `noteAmount = amount + changeAmount`; and `changeNote` commits to the change —
///         or is zero when `amount` consumes the note whole" — exactly what
///         `PrivateBondVault.withdraw` consumes to pay `dest` without ever touching the
///         passport.
/// @dev Fail-closed everywhere: a malformed blob, an arg the proof's public inputs do not
///      name, a failed deploy, or any revert inside the generated verifier reads as `false` —
///      never as a revert-shaped pass (the interface pins this).
///
///      The proof blob is `proof || public_inputs` (bb's layout): the trailing 192 bytes are
///      the six public inputs in circuit order — `token`, `dest`, `amount`, `changeNote`,
///      `nullBond`, `bondRoot`. `dest` is a public input the proof binds — any address the
///      owner names, named IN the proof: a relayer cannot redirect a withdraw it did not
///      prove, and the vault keeps its zero liveness dependency on any passport decoder.
///      `token` and `dest` are compared as numeric casts (right-aligned field elements),
///      `amount` raw so a value at or over p can never match. The Honk verifier itself is
///      deployed from committed initcode (`test/fixtures/verifiers/`, produced by
///      `bun circuits:prove`) — the main tree cannot compile it (via_ir vs the generated
///      dispatchers; see circuits/README.md) — and is called by address and selector,
///      never linked.
contract WithdrawVerifier is IWithdrawVerifier {
    /// @dev `verify(bytes,bytes32[])` — the generated ultra_honk verifier's only entrypoint.
    bytes4 internal constant VERIFY_SELECTOR = bytes4(keccak256("verify(bytes,bytes32[])"));

    /// @dev (token, dest, amount, changeNote, nullBond, bondRoot) — must mirror withdraw's
    ///      pub signature order.
    uint256 internal constant PUBLIC_INPUTS = 6;

    /// @dev The generated Honk verifier, deployed from initcode in the constructor. Zero
    ///      (deploy failed) fails every verify.
    address public immutable honkVerifier;

    constructor(bytes memory verifierInitcode) {
        address deployed;
        assembly {
            deployed := create(0, add(verifierInitcode, 0x20), mload(verifierInitcode))
        }
        honkVerifier = deployed;
    }

    /// @inheritdoc IWithdrawVerifier
    function verifyWithdraw(
        address token,
        address dest,
        uint256 amount,
        bytes32 changeNote,
        bytes32 nullBond,
        bytes32 bondRoot,
        bytes calldata proof
    ) external view returns (bool) {
        if (honkVerifier == address(0)) return false; // deploy failed — fail closed
        // A blob that cannot even carry the public inputs section is malformed: false,
        // never a panic (the empty-pubs path below would be an out-of-bounds read).
        if (proof.length < PUBLIC_INPUTS * 32) return false;
        (bytes32[] memory pubs, bytes calldata honkProof) = _split(proof);
        // The numeric cast, not a raw bytes20 cast: the proof's field element is the
        // address as an integer (right-aligned), while bytes32(bytes20) would left-align.
        if (pubs[0] != bytes32(uint256(uint160(token)))) return false; // raw address < p always
        if (pubs[1] != bytes32(uint256(uint160(dest)))) return false; // the proof's own dest
        if (pubs[2] != bytes32(amount)) return false; // raw amount; >= p can never match
        if (pubs[3] != changeNote) return false; // zero (whole) or the note the vault inserts
        if (pubs[4] != nullBond) return false; // the nullifier the vault will burn
        if (pubs[5] != bondRoot) return false; // the live root the vault gated
        return _verify(honkProof, pubs);
    }

    /// @dev Split the blob into the trailing public inputs and the proof body. Malformed
    ///      length returns empty pubs, which fails every caller's checks — never reverts.
    function _split(bytes calldata blob) internal pure returns (bytes32[] memory, bytes calldata) {
        if (blob.length < PUBLIC_INPUTS * 32) {
            return (new bytes32[](0), blob[0:0]);
        }
        uint256 proofLen = blob.length - PUBLIC_INPUTS * 32;
        bytes32[] memory pubs = new bytes32[](PUBLIC_INPUTS);
        for (uint256 i = 0; i < PUBLIC_INPUTS; i++) {
            pubs[i] = bytes32(blob[proofLen + i * 32:proofLen + (i + 1) * 32]);
        }
        return (pubs, blob[0:proofLen]);
    }

    /// @dev Call the generated verifier. `verify` is `view`: staticcall, so the adapter cannot
    ///      even be tricked into a state change; any revert or short/odd return is `false`.
    function _verify(bytes calldata honkProof, bytes32[] memory pubs) internal view returns (bool) {
        (bool ok, bytes memory ret) = honkVerifier.staticcall(abi.encodeWithSelector(VERIFY_SELECTOR, honkProof, pubs));
        return ok && ret.length == 32 && abi.decode(ret, (bool));
    }
}
