// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {PassportDecoderMock} from "../mocks/PassportDecoderMock.sol";
import {ClaimVerifierMock} from "../mocks/ClaimVerifierMock.sol";
import {HumanityRegistry} from "../src/packages/HumanityRegistry.sol";
import {RegistryHumanityVerifier} from "../src/packages/adapters/RegistryHumanityVerifier.sol";
import {RegistryAccountVerifier} from "../src/packages/adapters/RegistryAccountVerifier.sol";
import {PreparePassportVerifier} from "../src/packages/adapters/PreparePassportVerifier.sol";
import {PrepareAdmitVerifier} from "../src/packages/adapters/PrepareAdmitVerifier.sol";
import {PrivatePassport} from "../src/packages/PrivatePassport.sol";
import {PrivateReputation} from "../src/packages/PrivateReputation.sol";
import {PoseidonTree, DEFAULT_ROOT_HISTORY, MIN_ROOT_HISTORY, MAX_ROOT_HISTORY} from "../src/packages/PoseidonTree.sol";
import {PoseidonSingletons} from "./PoseidonSingletons.sol";

/// @title Prepare with real proofs (V2, PLURISWAP.md §3.15.4, §3.15.9)
/// @dev The activation bundle behind the REAL ultra_honk verifiers: register (V1's real
///      proofs) puts the genesis leaf into the account tree, then the two V2 prepares —
///      passport and admission — run on the committed fixtures (test/fixtures/proofs/,
///      generated by `bun circuits:prove` with the pinned toolchain) and the adapter-deployed
///      Honk contracts verify them on-chain. The admission proof computes the §3.14.7 tier
///      IN-CIRCUIT (T1 here: a fresh account, 100 units into flight of a 6-dec token, base
///      cap 250); the adapter's amplifications — the served token's own decimals and the
///      zero lockCommit of the vault-less V2 — are what the negatives pin.
///
///      This is the second interface pair (IPreparePassportVerifier, IPrepareAdmitVerifier)
///      whose mock is gone. The claim side (IClaimVerifier) and the vault side remain mocks
///      until V3, and are marked as such.
contract PrepareRealProofTest is Test {

    /// @dev The §3.14.7 pair tag. With a mock verifier nothing checks its VALUE — what these tests
    ///      exercise is that both sides of one activation carry the SAME one, which is what the module
    ///      compares. The real value is pinned by the fixture tests and by the circuit itself.
    /// @dev The REAL pair tag of the pinned sample: this suite runs against committed proofs, so the
    ///      value has to be the one the circuit committed to.
    function pairTag() internal view returns (bytes32) {
        return bytes32(vm.parseJsonUint(vectors, ".prepare.pair_tag"));
    }

    /// @dev A fresh deal id / counterparty per call: these tests predate the 2026-09-23 rule that credit
    ///      is once per counterparty, and they all mean "another deal with somebody new". The ones that
    ///      mean "the same somebody again" say so by passing a fixed tag.
    uint256 private _tagNonce;

    function _dealTag() internal returns (bytes32) {
        return keccak256(abi.encode("deal", ++_tagNonce));
    }

    function _cpTag() internal returns (bytes32) {
        return keccak256(abi.encode("counterparty", ++_tagNonce));
    }
    address internal constant FEE_TO = address(0xFEE);
    uint256 internal constant WALLET_KEY = 0xA11CE;

    string internal vectors;
    string internal proofHumanity;
    string internal proofAccount;
    string internal proofPassport;
    string internal proofAdmit;

    PassportDecoderMock internal decoder;
    HumanityRegistry internal registry;
    RegistryHumanityVerifier internal humanityVerifier;
    RegistryAccountVerifier internal accountVerifier;
    PreparePassportVerifier internal passportVerifier;
    PrepareAdmitVerifier internal admitVerifier;
    address internal anchor;
    address internal wallet;

    PoseidonTree internal accountTree;
    PrivatePassport internal passport;
    PrivateReputation internal reputation;

    bytes32 internal hsk;
    bytes32 internal hn;
    bytes32 internal leaf0;
    bytes32 internal dealId;
    bytes32 internal dealSubject;
    bytes32 internal repRoot;
    bytes32 internal newLeaf;
    bytes32 internal nullRep;
    address internal token;
    uint256 internal principal;
    uint256 internal deadline;

    function setUp() public {
        // The private layer hashes through the pinned poseidon-solidity singletons, which a test
        // EVM starts without (PLURISWAP.md §5.1).
        PoseidonSingletons.install();
        // forge's chain starts at timestamp 1: warp to a realistic clock so deadlines
        // carry meaning (the V1 lesson).
        vm.warp(1_700_000_000);
        deadline = block.timestamp + 2 hours;

        vectors = vm.readFile("test/fixtures/vectors.json");
        proofHumanity = vm.readFile("test/fixtures/proofs/register_humanity.json");
        proofAccount = vm.readFile("test/fixtures/proofs/register_account.json");
        proofPassport = vm.readFile("test/fixtures/proofs/prepare_passport.json");
        proofAdmit = vm.readFile("test/fixtures/proofs/prepare_admit.json");

        hsk = bytes32(vm.parseJsonUint(vectors, ".registry.hsk"));
        hn = bytes32(vm.parseJsonUint(vectors, ".registry.sample_hn"));
        leaf0 = bytes32(vm.parseJsonUint(vectors, ".registry.sample_leaf0"));
        dealId = bytes32(vm.parseJsonUint(vectors, ".prepare.deal_id"));
        dealSubject = bytes32(vm.parseJsonUint(vectors, ".prepare.deal_subject"));
        repRoot = bytes32(vm.parseJsonUint(vectors, ".prepare.root"));
        newLeaf = bytes32(vm.parseJsonUint(vectors, ".prepare.new_leaf"));
        nullRep = bytes32(vm.parseJsonUint(vectors, ".prepare.null_rep"));
        token = address(uint160(vm.parseJsonUint(vectors, ".prepare.token")));
        principal = vm.parseJsonUint(vectors, ".prepare.principal");

        // The pinned sample token is a synthetic address; the adapter's decimals
        // amplification reads `decimals()` on it, so a minimal 6-decimals oracle is etched
        // there (the proof's decimals pub is 6). A fresh address has no code: the read
        // fails closed, exactly like a token without the view.
        vm.etch(token, hex"600660005260206000f3"); // mstore(0, 6); return(0, 32)

        decoder = new PassportDecoderMock(200_000, 1 days);
        anchor = makeAddr("anchor");
        decoder.setScore(anchor, 200_000, uint64(block.timestamp + 30 days));
        registry = new HumanityRegistry(decoder, 0, bytes32(vm.parseJsonUint(vectors, ".registry.registry_id")));

        bytes32 commitment = registry.identityCommitmentOf(hsk);
        vm.prank(anchor);
        registry.enroll(commitment);

        humanityVerifier = new RegistryHumanityVerifier(
            registry, vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/register_humanity.json"), ".initcode")
        );
        accountVerifier = new RegistryAccountVerifier(
            registry, vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/register_account.json"), ".initcode")
        );
        passportVerifier = new PreparePassportVerifier(
            vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/prepare_passport.json"), ".initcode")
        );
        admitVerifier = new PrepareAdmitVerifier(
            vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/prepare_admit.json"), ".initcode")
        );

        // Every remaining mock is pre-deployed BEFORE the prediction (the tree's owner is
        // the reputation): an inline `new Mock()` inside a constructor-argument list would
        // consume a CREATE nonce of this test contract and drift the predicted address.
        ClaimVerifierMock claimProof = new ClaimVerifierMock(); // V3 replaces this

        address predictedRep = vm.computeCreateAddress(address(this), vm.getNonce(address(this)) + 2);
        accountTree = new PoseidonTree(32, DEFAULT_ROOT_HISTORY, predictedRep);
        passport = new PrivatePassport(accountTree, humanityVerifier, passportVerifier);
        reputation = new PrivateReputation(
            passport,
            accountTree,
            accountVerifier,
            admitVerifier,
            claimProof,
            FEE_TO,
            0,
            0,
            0,
            0,
            address(this),
            address(0)
        );
        assertEq(address(reputation), predictedRep, "predicted tree owner drifted");

        // Register the sample account with the V1 real-proof bundle: the account tree now
        // holds the genesis leaf0 both prepare proofs witness against.
        passport.register(proofHumanityBlob(), hn);
        reputation.register(proofAccountBlob(), hn, leaf0);
        assertEq(accountTree.nextIndex(), 1, "genesis leaf in");
        assertTrue(accountTree.isKnownRoot(repRoot), "the prepare root is the post-register root");

        wallet = vm.addr(WALLET_KEY);
    }

    function proofHumanityBlob() internal view returns (bytes memory) {
        return vm.parseJsonBytes(proofHumanity, ".proof_with_public_inputs");
    }

    function proofAccountBlob() internal view returns (bytes memory) {
        return vm.parseJsonBytes(proofAccount, ".proof_with_public_inputs");
    }

    function proofPassportBlob() internal view returns (bytes memory) {
        return vm.parseJsonBytes(proofPassport, ".proof_with_public_inputs");
    }

    function proofAdmitBlob() internal view returns (bytes memory) {
        return vm.parseJsonBytes(proofAdmit, ".proof_with_public_inputs");
    }

    /// @dev The wallet's EIP-712 consent over (dealId, dealSubject, module, deadline) —
    ///      the signature that pins a subject under a wallet (§3.15.4 "Firma de wallet").
    function _walletSig(address module) internal view returns (bytes memory) {
        bytes32 structHash = keccak256(
            abi.encode(
                keccak256("PrivatePrepare(bytes32 dealId,bytes32 dealSubject,address module,uint256 deadline)"),
                dealId,
                dealSubject,
                module,
                deadline
            )
        );
        bytes32 domainSeparator = keccak256(
            abi.encode(
                // OZ v5.5's constant, byte for byte: capital "I" in chainId.
                keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"),
                keccak256(bytes("PluriSwap")),
                keccak256(bytes("1")),
                block.chainid,
                module
            )
        );
        bytes32 digest = keccak256(abi.encodePacked("\x19\x01", domainSeparator, structHash));
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(WALLET_KEY, digest);
        return abi.encodePacked(r, s, v);
    }

    /// @dev The full activation side: passport prepare, admission prepare, then the kernel's
    ///      `admit` consuming the buffer.
    function _runBundle() internal {
        passport.prepare(
            wallet, dealId, dealSubject, repRoot, deadline, proofPassportBlob(), _walletSig(address(passport))
        );
        reputation.prepare(
            wallet,
            dealId,
            dealSubject,
            newLeaf,
            nullRep,
            token,
            principal,
            bytes32(0),
            repRoot,
            pairTag(),
            deadline,
            proofAdmitBlob(),
            _walletSig(address(reputation))
        );
    }

    // ---------------------------------------------------------------- the bundle, green path

    function test_prepare_bundleWithRealProofs() public {
        // forge checks the whole expected-log queue at the NEXT call boundary: each
        // expectEmit must be immediately followed by the call that emits it.
        vm.expectEmit(true, true, true, true, address(passport));
        emit PrivatePassport.PassportPrepared(wallet, dealSubject, deadline);
        passport.prepare(
            wallet, dealId, dealSubject, repRoot, deadline, proofPassportBlob(), _walletSig(address(passport))
        );

        vm.expectEmit(true, true, true, true, address(reputation));
        emit PrivateReputation.ReputationPrepared(wallet, dealSubject, newLeaf, deadline);
        reputation.prepare(
            wallet,
            dealId,
            dealSubject,
            newLeaf,
            nullRep,
            token,
            principal,
            bytes32(0),
            repRoot,
            pairTag(),
            deadline,
            proofAdmitBlob(),
            _walletSig(address(reputation))
        );

        // The nullifier of version 0 burned, the new leaf inserted (index 1), the buffers
        // exactly as the kernel's engage consumes them.
        assertTrue(accountTree.isSpent(nullRep));
        assertEq(accountTree.nextIndex(), 2);

        assertEq(passport.identify(wallet), dealSubject);

        vm.expectEmit(true, true, true, true, address(reputation));
        emit PrivateReputation.Admitted(wallet, dealSubject, token, principal);
        bytes32 subject = reputation.admit(wallet, _dealTag(), token, principal, address(0));
        assertEq(subject, dealSubject);

        // The admit deleted the buffer: a second admit has nothing to match (NoPrepare).
        vm.expectRevert(PrivateReputation.NoPrepare.selector);
        reputation.admit(wallet, _dealTag(), token, principal, address(0));
    }

    function test_prepare_admit_replayDiesOnTheNullifier() public {
        _runBundle();
        // The proof itself is valid forever, but the version-0 nullifier is spent: the
        // transition cannot be replayed — the module rejects before the tree can grow.
        vm.expectRevert(PoseidonTree.NullifierUsed.selector);
        reputation.prepare(
            wallet,
            dealId,
            dealSubject,
            newLeaf,
            nullRep,
            token,
            principal,
            bytes32(0),
            repRoot,
            pairTag(),
            deadline,
            proofAdmitBlob(),
            _walletSig(address(reputation))
        );
    }

    // ---------------------------------------------------------------- adapter negatives

    function test_verifyPassport_rejectsWrongArgs() public view {
        bytes32 wrongSubject = bytes32(uint256(keccak256("other-subject")));
        bytes32 wrongRoot = bytes32(uint256(keccak256("other-root")));
        assertTrue(passportVerifier.verifyPassport(dealSubject, repRoot, proofPassportBlob()));
        assertFalse(passportVerifier.verifyPassport(wrongSubject, repRoot, proofPassportBlob()));
        assertFalse(passportVerifier.verifyPassport(dealSubject, wrongRoot, proofPassportBlob()));
    }

    function test_verifyAdmit_rejectsWrongArgs() public {
        bytes32 wrongSubject = bytes32(uint256(keccak256("other-subject")));
        bytes32 wrongLeaf = bytes32(uint256(0xBEEF));
        bytes32 wrongNull = bytes32(uint256(keccak256("other-null")));
        bytes32 wrongRoot = bytes32(uint256(keccak256("other-root")));
        address wrongToken = makeAddr("not-the-token");
        uint256 wrongPrincipal = principal + 1;

        assertTrue(
            admitVerifier.verifyAdmit(
                dealSubject, newLeaf, nullRep, token, principal, bytes32(0), repRoot, pairTag(), proofAdmitBlob()
            )
        );
        assertFalse(
            admitVerifier.verifyAdmit(
                wrongSubject, newLeaf, nullRep, token, principal, bytes32(0), repRoot, pairTag(), proofAdmitBlob()
            )
        );
        assertFalse(
            admitVerifier.verifyAdmit(
                dealSubject, wrongLeaf, nullRep, token, principal, bytes32(0), repRoot, pairTag(), proofAdmitBlob()
            )
        );
        assertFalse(
            admitVerifier.verifyAdmit(
                dealSubject, newLeaf, wrongNull, token, principal, bytes32(0), repRoot, pairTag(), proofAdmitBlob()
            )
        );
        assertFalse(
            admitVerifier.verifyAdmit(
                dealSubject, newLeaf, nullRep, wrongToken, principal, bytes32(0), repRoot, pairTag(), proofAdmitBlob()
            )
        );
        assertFalse(
            admitVerifier.verifyAdmit(
                dealSubject, newLeaf, nullRep, token, wrongPrincipal, bytes32(0), repRoot, pairTag(), proofAdmitBlob()
            )
        );
        assertFalse(
            admitVerifier.verifyAdmit(
                dealSubject, newLeaf, nullRep, token, principal, bytes32(0), wrongRoot, pairTag(), proofAdmitBlob()
            )
        );
    }

    function test_verifyAdmit_rejectsNonZeroLockCommit() public {
        // V2 has no vault: the bond column of §3.14.7 (the higher caps) is selected by a
        // non-zero lockCommit, and without a vault to bind the lock it would be bought for
        // free. The adapter amplifies the interface's "zero without bonds" into a rejection.
        bytes32 lockCommit = bytes32(uint256(keccak256("phantom-lock")));
        assertFalse(
            admitVerifier.verifyAdmit(
                dealSubject, newLeaf, nullRep, token, principal, lockCommit, repRoot, pairTag(), proofAdmitBlob()
            )
        );

        vm.expectRevert(PrivateReputation.AdmitProofFailed.selector);
        reputation.prepare(
            wallet,
            dealId,
            dealSubject,
            newLeaf,
            nullRep,
            token,
            principal,
            lockCommit,
            repRoot,
            pairTag(),
            deadline,
            proofAdmitBlob(),
            _walletSig(address(reputation))
        );
    }

    function test_verifyAdmit_rejectsForeignDecimals() public {
        // The same proof, same token address, but the SERVED token now reports 18 decimals:
        // the tier scale the proof computed with (250 * 10^6) belongs to another token
        // — the amplification reads the live token, not the proof's claim.
        vm.etch(token, hex"601260005260206000f3"); // mstore(0, 18); return(0, 32)
        assertFalse(
            admitVerifier.verifyAdmit(
                dealSubject, newLeaf, nullRep, token, principal, bytes32(0), repRoot, pairTag(), proofAdmitBlob()
            )
        );
    }

    function test_verifyAdmit_rejectsSilentToken() public {
        // A token that reverts on `decimals()` (or has no code at all) reads as the
        // sentinel: no proof can name it, admission fails closed.
        vm.etch(token, hex"60006000fd"); // revert(0, 0)
        assertFalse(
            admitVerifier.verifyAdmit(
                dealSubject, newLeaf, nullRep, token, principal, bytes32(0), repRoot, pairTag(), proofAdmitBlob()
            )
        );
    }

    function test_verify_rejectsTamperedProof() public view {
        bytes memory blob = proofAdmitBlob();
        blob[42] = blob[42] ^ 0xff; // one byte inside the proof body
        assertFalse(
            admitVerifier.verifyAdmit(dealSubject, newLeaf, nullRep, token, principal, bytes32(0), repRoot, pairTag(), blob)
        );

        blob = proofPassportBlob();
        blob[42] = blob[42] ^ 0xff;
        assertFalse(passportVerifier.verifyPassport(dealSubject, repRoot, blob));
    }

    function test_verify_rejectsMalformedBlobs() public view {
        // Short blobs and truncated public-input sections read as false, never revert-shaped.
        assertFalse(passportVerifier.verifyPassport(dealSubject, repRoot, hex"0011"));
        assertFalse(
            admitVerifier.verifyAdmit(dealSubject, newLeaf, nullRep, token, principal, bytes32(0), repRoot, pairTag(), hex"0011")
        );
        assertFalse(
            admitVerifier.verifyAdmit(
                dealSubject, newLeaf, nullRep, token, principal, bytes32(0), repRoot, pairTag(), _truncate(proofAdmitBlob(), 64)
            )
        );
    }

    function test_verify_rejectsCrossCircuitProofs() public view {
        // The passport blob carries 2 pubs, the admit blob 9: into the passport verifier the
        // admit blob's tail splits as (repRoot, decimals) — neither arg matches; into the
        // admit verifier the passport blob is too short to carry 9 pubs at all.
        assertFalse(passportVerifier.verifyPassport(dealSubject, repRoot, proofAdmitBlob()));
        assertFalse(
            admitVerifier.verifyAdmit(
                dealSubject, newLeaf, nullRep, token, principal, bytes32(0), repRoot, pairTag(), proofPassportBlob()
            )
        );
        // The register blobs are equally foreign here (3 pubs, register statements).
        assertFalse(passportVerifier.verifyPassport(dealSubject, repRoot, proofHumanityBlob()));
        assertFalse(
            admitVerifier.verifyAdmit(
                dealSubject, newLeaf, nullRep, token, principal, bytes32(0), repRoot, pairTag(), proofAccountBlob()
            )
        );
    }

    function test_prepare_rejectsForeignRoot() public {
        // The module gates the root against the account tree's ring buffer before the
        // proof: an unknown root never reaches the verifier.
        bytes32 foreign = bytes32(uint256(keccak256("never-inserted")));
        vm.expectRevert(PrivatePassport.UnknownRoot.selector);
        passport.prepare(
            wallet, dealId, dealSubject, foreign, deadline, proofPassportBlob(), _walletSig(address(passport))
        );
        vm.expectRevert(PrivateReputation.UnknownRoot.selector);
        reputation.prepare(
            wallet,
            dealId,
            dealSubject,
            newLeaf,
            nullRep,
            token,
            principal,
            bytes32(0),
            foreign,
            pairTag(),
            deadline,
            proofAdmitBlob(),
            _walletSig(address(reputation))
        );
    }

    function test_prepare_rejectsBadWalletSignature() public {
        bytes memory sig = _walletSig(address(passport));
        sig[10] = sig[10] ^ 0xff; // a broken signature cannot pin a subject under a wallet
        vm.expectRevert(PrivatePassport.InvalidWalletSignature.selector);
        passport.prepare(wallet, dealId, dealSubject, repRoot, deadline, proofPassportBlob(), sig);

        sig = _walletSig(address(reputation));
        sig[10] = sig[10] ^ 0xff;
        vm.expectRevert(PrivateReputation.InvalidWalletSignature.selector);
        reputation.prepare(
            wallet,
            dealId,
            dealSubject,
            newLeaf,
            nullRep,
            token,
            principal,
            bytes32(0),
            repRoot,
            pairTag(),
            deadline,
            proofAdmitBlob(),
            sig
        );
    }

    /// LEVER 3: where a prepare's gas actually goes. The published ~7.6M for a one-sided bundle came
    /// from forge's per-test figure, which counts the cheatcodes that read fixtures off disk — the
    /// same thing that inflated the per-verify numbers by 2.6x. Measured with every input hoisted out
    /// of the window, a prepare is its verify plus its tree work plus very little else.
    function test_lever_bundleDecomposition() public {
        bytes memory passportBlob = proofPassportBlob();
        bytes memory admitBlob = proofAdmitBlob();
        bytes memory passportSig = _walletSig(address(passport));
        bytes memory admitSig = _walletSig(address(reputation));
        bytes32 tag = pairTag();

        uint256 before = gasleft();
        passport.prepare(wallet, dealId, dealSubject, repRoot, deadline, passportBlob, passportSig);
        uint256 passportPrepare = before - gasleft();

        before = gasleft();
        reputation.prepare(
            wallet, dealId, dealSubject, newLeaf, nullRep, token, principal, bytes32(0), repRoot, tag, deadline,
            admitBlob, admitSig
        );
        uint256 repPrepare = before - gasleft();

        before = gasleft();
        reputation.admit(wallet, _dealTag(), token, principal, address(0));
        uint256 admit = before - gasleft();

        emit log_named_uint("passport.prepare (verify 717k + sig + storage)", passportPrepare);
        emit log_named_uint("reputation.prepare (verify 730k + spend + insert + storage)", repPrepare);
        emit log_named_uint("reputation.admit (no proof: buffer + identify)", admit);
        emit log_named_uint("one side, passport+rep, total", passportPrepare + repPrepare + admit);
        // A bonded deal adds the vault's own prepare; a two-sided deal doubles all of it. The number
        // that matters for §3.15.4 is this one times two, plus the kernel's activation.
    }

    // ---------------------------------------------------------------- gas of the real verify

    function test_verify_gas() public {
        // Everything the call needs is read BEFORE the window. `pairTag()` parses vectors.json through
        // a cheatcode, and a cheatcode inside the measurement is the measurement: it read as ~4M of
        // verifier gas that the verifier never spent (2026-09-23).
        bytes memory passportBlob = proofPassportBlob();
        bytes memory admitBlob = proofAdmitBlob();
        bytes32 tag = pairTag();

        uint256 before = gasleft();
        passportVerifier.verifyPassport(dealSubject, repRoot, passportBlob);
        uint256 passportCost = before - gasleft();

        before = gasleft();
        admitVerifier.verifyAdmit(dealSubject, newLeaf, nullRep, token, principal, bytes32(0), repRoot, tag, admitBlob);
        uint256 admitCost = before - gasleft();

        emit log_named_uint("verifyPassport gas", passportCost);
        emit log_named_uint("verifyAdmit gas", admitCost);
    }

    /// @dev Solidity cannot slice memory bytes; the truncated-blob tests need copies.
    function _truncate(bytes memory b, uint256 n) internal pure returns (bytes memory) {
        bytes memory out = new bytes(n);
        for (uint256 i = 0; i < n; i++) {
            out[i] = b[i];
        }
        return out;
    }
}
