// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {PassportDecoderMock} from "../mocks/PassportDecoderMock.sol";
import {ClaimVerifierMock} from "../mocks/ClaimVerifierMock.sol";
import {HumanityRegistry} from "../src/packages/HumanityRegistry.sol";
import {RegistryHumanityVerifier} from "../src/packages/adapters/RegistryHumanityVerifier.sol";
import {RegistryAccountVerifier} from "../src/packages/adapters/RegistryAccountVerifier.sol";
import {BundleVerifier} from "../src/packages/adapters/BundleVerifier.sol";
import {IBundleVerifier} from "../src/packages/interfaces/IBundleVerifier.sol";
import {PrivatePassport} from "../src/packages/PrivatePassport.sol";
import {PrivateReputation} from "../src/packages/PrivateReputation.sol";
import {PoseidonTree, DEFAULT_ROOT_HISTORY, MIN_ROOT_HISTORY, MAX_ROOT_HISTORY} from "../src/packages/PoseidonTree.sol";
import {PoseidonSingletons} from "./PoseidonSingletons.sol";

/// @title Prepare with real proofs (V2, PLURISWAP.md §3.15.4, §3.15.9)
/// @dev The activation bundle behind the REAL ultra_honk verifiers: register (V1's real
///      proofs) puts the genesis leaf into the account tree, then the two V2 prepares —
///      passport and admission — run on the committed fixtures (test/fixtures/proofs/,
///      generated by `bun circuits:prove` with the pinned toolchain) and the adapter-deployed
///      Honk contracts verify them on-chain. The admission proof computes the §3.14.7 tier
///      IN-CIRCUIT (T1 here: a fresh account, 100 units into flight of a 6-dec token, base
///      cap 250); the adapter's amplifications — the served token's own decimals and the
///      zero lockCommit of the vault-less V2 — are what the negatives pin.
///
///      This is the second interface pair (IPreparePassportVerifier, IPrepareAdmitVerifier)
///      whose mock is gone. The claim side (IClaimVerifier) and the vault side remain mocks
///      until V3, and are marked as such.
contract PrepareRealProofTest is Test {

    /// @dev The §3.14.7 pair tag. With a mock verifier nothing checks its VALUE — what these tests
    ///      exercise is that both sides of one activation carry the SAME one, which is what the module
    ///      compares. The real value is pinned by the fixture tests and by the circuit itself.
    /// @dev The REAL pair tag of the pinned sample: this suite runs against committed proofs, so the
    ///      value has to be the one the circuit committed to.
    function pairTag() internal view returns (bytes32) {
        return bytes32(vm.parseJsonUint(vectors, ".prepare.pair_tag"));
    }

    /// @dev A fresh deal id / counterparty per call: these tests predate the 2026-09-23 rule that credit
    ///      is once per counterparty, and they all mean "another deal with somebody new". The ones that
    ///      mean "the same somebody again" say so by passing a fixed tag.
    uint256 private _tagNonce;

    function _dealTag() internal returns (bytes32) {
        return keccak256(abi.encode("deal", ++_tagNonce));
    }

    function _cpTag() internal returns (bytes32) {
        return keccak256(abi.encode("counterparty", ++_tagNonce));
    }
    address internal constant FEE_TO = address(0xFEE);
    uint256 internal constant WALLET_KEY = 0xA11CE;

    string internal vectors;
    string internal proofHumanity;
    string internal proofAccount;
    string internal proofSide;

    PassportDecoderMock internal decoder;
    HumanityRegistry internal registry;
    RegistryHumanityVerifier internal humanityVerifier;
    RegistryAccountVerifier internal accountVerifier;
    BundleVerifier internal bundle;
    address internal anchor;
    address internal wallet;

    PoseidonTree internal accountTree;
    PrivatePassport internal passport;
    PrivateReputation internal reputation;

    bytes32 internal hsk;
    bytes32 internal hn;
    bytes32 internal leaf0;
    bytes32 internal dealId;
    bytes32 internal dealSubject;
    bytes32 internal repRoot;
    bytes32 internal newLeaf;
    bytes32 internal nullRep;
    address internal token;
    uint256 internal principal;
    uint256 internal deadline;

    function setUp() public {
        // The private layer hashes through the pinned poseidon-solidity singletons, which a test
        // EVM starts without (PLURISWAP.md §5.1).
        PoseidonSingletons.install();
        // forge's chain starts at timestamp 1: warp to a realistic clock so deadlines
        // carry meaning (the V1 lesson).
        vm.warp(1_700_000_000);
        deadline = block.timestamp + 2 hours;

        vectors = vm.readFile("test/fixtures/vectors.json");
        proofHumanity = vm.readFile("test/fixtures/proofs/register_humanity.json");
        proofAccount = vm.readFile("test/fixtures/proofs/register_account.json");
        proofSide = vm.readFile("test/fixtures/proofs/prepare_side.json");

        hsk = bytes32(vm.parseJsonUint(vectors, ".registry.hsk"));
        hn = bytes32(vm.parseJsonUint(vectors, ".registry.sample_hn"));
        leaf0 = bytes32(vm.parseJsonUint(vectors, ".registry.sample_leaf0"));
        dealId = bytes32(vm.parseJsonUint(vectors, ".prepare.deal_id"));
        dealSubject = bytes32(vm.parseJsonUint(vectors, ".prepare.deal_subject"));
        repRoot = bytes32(vm.parseJsonUint(vectors, ".prepare.root"));
        newLeaf = bytes32(vm.parseJsonUint(vectors, ".prepare.new_leaf"));
        nullRep = bytes32(vm.parseJsonUint(vectors, ".prepare.null_rep"));
        token = address(uint160(vm.parseJsonUint(vectors, ".prepare.token")));
        principal = vm.parseJsonUint(vectors, ".prepare.principal");

        // The pinned sample token is a synthetic address; the adapter's decimals
        // amplification reads `decimals()` on it, so a minimal 6-decimals oracle is etched
        // there (the proof's decimals pub is 6). A fresh address has no code: the read
        // fails closed, exactly like a token without the view.
        vm.etch(token, hex"600660005260206000f3"); // mstore(0, 6); return(0, 32)

        decoder = new PassportDecoderMock(200_000, 1 days);
        anchor = makeAddr("anchor");
        decoder.setScore(anchor, 200_000, uint64(block.timestamp + 30 days));
        registry = new HumanityRegistry(decoder, 0, bytes32(vm.parseJsonUint(vectors, ".registry.registry_id")));

        bytes32 commitment = registry.identityCommitmentOf(hsk);
        vm.prank(anchor);
        registry.enroll(commitment);

        humanityVerifier = new RegistryHumanityVerifier(
            registry, vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/register_humanity.json"), ".initcode")
        );
        accountVerifier = new RegistryAccountVerifier(
            registry, vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/register_account.json"), ".initcode")
        );
        bundle = new BundleVerifier(
            vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/prepare_side.json"), ".initcode")
        );

        // Every remaining mock is pre-deployed BEFORE the prediction (the tree's owner is
        // the reputation): an inline `new Mock()` inside a constructor-argument list would
        // consume a CREATE nonce of this test contract and drift the predicted address.
        ClaimVerifierMock claimProof = new ClaimVerifierMock(); // V3 replaces this

        address predictedRep = vm.computeCreateAddress(address(this), vm.getNonce(address(this)) + 2);
        accountTree = new PoseidonTree(32, DEFAULT_ROOT_HISTORY, predictedRep);
        passport = new PrivatePassport(accountTree, humanityVerifier, bundle);
        reputation = new PrivateReputation(
            passport,
            accountTree,
            accountVerifier,
            bundle,
            claimProof,
            FEE_TO,
            0,
            0,
            0,
            0,
            address(this),
            address(0)
        );
        assertEq(address(reputation), predictedRep, "predicted tree owner drifted");

        // Register the sample account with the V1 real-proof bundle: the account tree now
        // holds the genesis leaf0 both prepare proofs witness against.
        passport.register(proofHumanityBlob(), hn);
        reputation.register(proofAccountBlob(), hn, leaf0);
        assertEq(accountTree.nextIndex(), 1, "genesis leaf in");
        assertTrue(accountTree.isKnownRoot(repRoot), "the prepare root is the post-register root");

        wallet = vm.addr(WALLET_KEY);
    }

    function proofHumanityBlob() internal view returns (bytes memory) {
        return vm.parseJsonBytes(proofHumanity, ".proof_with_public_inputs");
    }

    function proofAccountBlob() internal view returns (bytes memory) {
        return vm.parseJsonBytes(proofAccount, ".proof_with_public_inputs");
    }

    /// The side as the merged circuit proved it (§3.15.4): the bonded shape, because the fixture is.
    /// The vault is absent from this suite, so nothing here reads `bondRoot` — what the passport and
    /// the reputation read is their own half, out of the same inputs.
    function side() internal view returns (IBundleVerifier.BundleInputs memory) {
        return IBundleVerifier.BundleInputs({
            dealSubject: dealSubject,
            dealId: dealId,
            token: token,
            principal: principal,
            repRoot: repRoot,
            newLeaf: newLeaf,
            nullRep: nullRep,
            pairTag: pairTag(),
            lockCommit: bytes32(vm.parseJsonUint(vectors, ".side.lock_commit")),
            lockAmount: vm.parseJsonUint(vectors, ".side.lock_amount"),
            changeNote: bytes32(vm.parseJsonUint(vectors, ".side.change_note")),
            nullBond: bytes32(vm.parseJsonUint(vectors, ".side.null_bond")),
            bondRoot: bytes32(vm.parseJsonUint(vectors, ".side.bond_root"))
        });
    }

    function proofSideBlob() internal view returns (bytes memory) {
        return vm.parseJsonBytes(proofSide, ".proof_with_public_inputs");
    }

    /// @dev Every module reads a ticket, so every flow starts by leaving one.
    function _prove() internal {
        require(bundle.verify(side(), proofSideBlob()), "the committed side proof must verify");
    }

    /// @dev The wallet's EIP-712 consent over (dealId, dealSubject, module, deadline) —
    ///      the signature that pins a subject under a wallet (§3.15.4 "Firma de wallet").
    function _walletSig(address module) internal view returns (bytes memory) {
        bytes32 structHash = keccak256(
            abi.encode(
                keccak256("PrivatePrepare(bytes32 dealId,bytes32 dealSubject,address module,uint256 deadline)"),
                dealId,
                dealSubject,
                module,
                deadline
            )
        );
        bytes32 domainSeparator = keccak256(
            abi.encode(
                // OZ v5.5's constant, byte for byte: capital "I" in chainId.
                keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"),
                keccak256(bytes("PluriSwap")),
                keccak256(bytes("1")),
                block.chainid,
                module
            )
        );
        bytes32 digest = keccak256(abi.encodePacked("\x19\x01", domainSeparator, structHash));
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(WALLET_KEY, digest);
        return abi.encodePacked(r, s, v);
    }

    /// @dev The full activation side: passport prepare, admission prepare, then the kernel's
    ///      `admit` consuming the buffer.
    function _runBundle() internal {
        _prove();
        passport.prepare(side(), wallet, deadline, _walletSig(address(passport)));
        reputation.prepare(
            PrivateReputation.Side({inputs: side(), wallet: wallet, walletSig: _walletSig(address(reputation))}),
            deadline
        );
    }

    // ---------------------------------------------------------------- the bundle, green path

    function test_prepare_bundleWithRealProofs() public {
        // forge checks the whole expected-log queue at the NEXT call boundary: each
        // expectEmit must be immediately followed by the call that emits it.
        // One proof for the whole side, verified once (§3.15.4); after this the modules only ask.
        _prove();

        vm.expectEmit(true, true, true, true, address(passport));
        emit PrivatePassport.PassportPrepared(wallet, dealSubject, deadline);
        passport.prepare(side(), wallet, deadline, _walletSig(address(passport)));

        vm.expectEmit(true, true, true, true, address(reputation));
        emit PrivateReputation.ReputationPrepared(wallet, dealSubject, newLeaf, deadline);
        reputation.prepare(
            PrivateReputation.Side({inputs: side(), wallet: wallet, walletSig: _walletSig(address(reputation))}),
            deadline
        );

        // The nullifier of version 0 burned, the new leaf inserted (index 1), the buffers
        // exactly as the kernel's engage consumes them.
        assertTrue(accountTree.isSpent(nullRep));
        assertEq(accountTree.nextIndex(), 2);

        assertEq(passport.identify(wallet), dealSubject);

        vm.expectEmit(true, true, true, true, address(reputation));
        emit PrivateReputation.Admitted(wallet, dealSubject, token, principal);
        bytes32 subject = reputation.admit(wallet, _dealTag(), token, principal, address(0));
        assertEq(subject, dealSubject);

        // The admit deleted the buffer: a second admit has nothing to match (NoPrepare).
        vm.expectRevert(PrivateReputation.NoPrepare.selector);
        reputation.admit(wallet, _dealTag(), token, principal, address(0));
    }

    function test_prepare_admit_replayDiesOnTheNullifier() public {
        _runBundle();
        // The proof itself is valid forever, but the version-0 nullifier is spent: the
        // transition cannot be replayed — the module rejects before the tree can grow.
        PrivateReputation.Side memory again =
            PrivateReputation.Side({inputs: side(), wallet: wallet, walletSig: _walletSig(address(reputation))});
        vm.expectRevert(PoseidonTree.NullifierUsed.selector);
        reputation.prepare(again, deadline);
    }

    // ---------------------------------------------------------------- adapter negatives









    function test_prepare_rejectsForeignRoot() public {
        // The modules gate the root against their own tree's ring buffer BEFORE asking the shared
        // verifier anything: an unknown root never reaches a ticket lookup, let alone a verification.
        _prove();
        IBundleVerifier.BundleInputs memory foreignSide = side();
        foreignSide.repRoot = bytes32(uint256(keccak256("never-inserted")));
        bytes memory pSig = _walletSig(address(passport));
        bytes memory rSig = _walletSig(address(reputation));

        vm.expectRevert(PrivatePassport.UnknownRoot.selector);
        passport.prepare(foreignSide, wallet, deadline, pSig);

        PrivateReputation.Side memory foreign =
            PrivateReputation.Side({inputs: foreignSide, wallet: wallet, walletSig: rSig});
        vm.expectRevert(PrivateReputation.UnknownRoot.selector);
        reputation.prepare(foreign, deadline);
    }

    /// The other half of the same guard: a root the tree knows, but a side nobody proved. The ticket
    /// is content-keyed, so an edited field is simply a side that was never verified.
    function test_prepare_rejectsASideThatWasNotProven() public {
        _prove();
        IBundleVerifier.BundleInputs memory edited = side();
        edited.newLeaf = keccak256("a leaf nobody proved");
        bytes memory rSig = _walletSig(address(reputation));
        PrivateReputation.Side memory bad =
            PrivateReputation.Side({inputs: edited, wallet: wallet, walletSig: rSig});
        vm.expectRevert(PrivateReputation.AdmitProofFailed.selector);
        reputation.prepare(bad, deadline);
    }

    /// And without any ticket at all — the relayer forgot to verify — every module fails closed.
    function test_prepare_withoutATicketFailsClosed() public {
        bytes memory pSig = _walletSig(address(passport));
        IBundleVerifier.BundleInputs memory s_ = side();
        vm.expectRevert(PrivatePassport.PassportProofFailed.selector);
        passport.prepare(s_, wallet, deadline, pSig);
    }

    function test_prepare_rejectsBadWalletSignature() public {
        // A proof says the account consents to the TRANSITION; the signature says the wallet consents
        // to this deal under this module. Sharing the proof did not merge the consents: each module
        // still has its own EIP-712 domain, and a broken signature stops each one on its own.
        _prove();
        IBundleVerifier.BundleInputs memory s_ = side();

        bytes memory sig = _walletSig(address(passport));
        sig[10] = sig[10] ^ 0xff;
        vm.expectRevert(PrivatePassport.InvalidWalletSignature.selector);
        passport.prepare(s_, wallet, deadline, sig);

        bytes memory rsig = _walletSig(address(reputation));
        rsig[10] = rsig[10] ^ 0xff;
        PrivateReputation.Side memory bad = PrivateReputation.Side({inputs: s_, wallet: wallet, walletSig: rsig});
        vm.expectRevert(PrivateReputation.InvalidWalletSignature.selector);
        reputation.prepare(bad, deadline);
    }

    /// LEVER 3: where a prepare's gas actually goes. The published ~7.6M for a one-sided bundle came
    /// from forge's per-test figure, which counts the cheatcodes that read fixtures off disk — the
    /// same thing that inflated the per-verify numbers by 2.6x. Measured with every input hoisted out
    /// of the window, a prepare is its verify plus its tree work plus very little else.
    /// Where one side's gas goes, now that the three statements are one proof (§3.15.4). The
    /// verification is paid ONCE, by whoever submits the proof; what the modules pay afterwards is a
    /// ticket lookup and their own storage.
    function test_lever_bundleDecomposition() public {
        IBundleVerifier.BundleInputs memory s_ = side();
        bytes memory blob = proofSideBlob();
        bytes memory passportSig = _walletSig(address(passport));
        bytes memory admitSig = _walletSig(address(reputation));
        PrivateReputation.Side memory repSide =
            PrivateReputation.Side({inputs: s_, wallet: wallet, walletSig: admitSig});

        uint256 before = gasleft();
        bundle.verify(s_, blob);
        uint256 verification = before - gasleft();

        before = gasleft();
        passport.prepare(s_, wallet, deadline, passportSig);
        uint256 passportPrepare = before - gasleft();

        before = gasleft();
        reputation.prepare(repSide, deadline);
        uint256 repPrepare = before - gasleft();

        before = gasleft();
        reputation.admit(wallet, _dealTag(), token, principal, address(0));
        uint256 admit = before - gasleft();

        emit log_named_uint("bundle.verify (once for the whole side)", verification);
        emit log_named_uint("passport.prepare (ticket + sig + storage)", passportPrepare);
        emit log_named_uint("reputation.prepare (ticket + spend + insert + storage)", repPrepare);
        emit log_named_uint("reputation.admit (buffer + identify)", admit);
        emit log_named_uint("one side, total", verification + passportPrepare + repPrepare + admit);
    }

    /// @dev Solidity cannot slice memory bytes; the truncated-blob tests need copies.
    function _truncate(bytes memory b, uint256 n) internal pure returns (bytes memory) {
        bytes memory out = new bytes(n);
        for (uint256 i = 0; i < n; i++) {
            out[i] = b[i];
        }
        return out;
    }
}
