// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {PoseidonTree, DEFAULT_ROOT_HISTORY, MIN_ROOT_HISTORY, MAX_ROOT_HISTORY} from "../src/packages/PoseidonTree.sol";
import {PrivacyCommitments} from "../src/packages/libraries/PrivacyCommitments.sol";
import {PoseidonSingletons} from "./PoseidonSingletons.sol";

/// @title PrivacyCommitments parity tests (V0, PLURISWAP.md §3.15.3 as amended)
/// @dev The Solidity twin against test/fixtures/vectors.json — generated by `bun circuits:vectors`
///      from the JS twin, and pinned inside the Noir crate by circuits/crates/pluri_commitments
///      (`nargo test`). Three languages, one fixture: if these tests pass, on-chain Poseidon
///      (poseidon-solidity), the circuits (Noir) and the prover-side tooling (circomlibjs) agree
///      byte for byte on every commitment of the private layer.
contract PrivacyCommitmentsTest is Test {
    /// @dev The BN254 scalar field. The pinned rule: every bytes32 input is interpreted mod p.
    uint256 internal constant BN254_P = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    uint256 internal constant DEPTH = 8;

    string internal vectors;
    PoseidonTree internal tree;

    function setUp() public {
        // The private layer hashes through the pinned poseidon-solidity singletons, which a test
        // EVM starts without (PLURISWAP.md §5.1).
        PoseidonSingletons.install();
        vectors = vm.readFile("test/fixtures/vectors.json");
        tree = new PoseidonTree(uint8(DEPTH), DEFAULT_ROOT_HISTORY, address(this));
    }

    // ---------------------------------------------------------------- primitives

    function test_fixtureProvenance() public view {
        // Guards a stale fixture: the vectors must come from the canonical generator.
        assertEq(vm.parseJsonString(vectors, ".provenance.generator"), "circuits/js/vectors.ts (bun circuits:vectors)");
    }

    function test_poseidonT3_matchesVector() public view {
        // t3[0] is the circomlib poseidonperm_x5_254_3([1, 2]) vector — the same
        // constant PoseidonTree.t.sol pins — so all three twins sit on the pinned params.
        assertEq(
            PrivacyCommitments.poseidonT3(bytes32(uint256(1)), bytes32(uint256(2))), _out(".poseidon.t3[0].output")
        );
    }

    function test_poseidonT3_highEdgeMatchesVector() public view {
        uint256 a = vm.parseJsonUint(vectors, ".poseidon.t3[2].inputs[0]");
        uint256 b = vm.parseJsonUint(vectors, ".poseidon.t3[2].inputs[1]");
        // p-1 is the largest field element: the permutation must not leave the field.
        assertEq(a, BN254_P - 1);
        assertEq(PrivacyCommitments.poseidonT3(bytes32(a), bytes32(b)), _out(".poseidon.t3[2].output"));
    }

    // ---------------------------------------------------------------- builders

    function test_accountCommitment() public view {
        bytes32 skId = bytes32(_in(".builders.s.sk_id"));
        assertEq(PrivacyCommitments.accountCommitment(skId), _out(".builders.s.output"));
    }

    function test_hn() public view {
        // registry_id is a raw keccak256 output (>= p): the mod-p rule is pinned here.
        uint256 rawRegistryId = _in(".builders.hn.registry_id");
        assertGt(rawRegistryId, BN254_P);
        assertEq(
            PrivacyCommitments.hn(bytes32(_in(".builders.hn.anchor")), bytes32(rawRegistryId)),
            _out(".builders.hn.output")
        );
    }

    function test_dealSubject() public view {
        // deal_id is a raw keccak256 output (>= p): the mod-p rule is pinned here too.
        uint256 rawDealId = _in(".builders.deal_subject.deal_id");
        assertGt(rawDealId, BN254_P);
        assertEq(
            PrivacyCommitments.dealSubject(bytes32(_in(".builders.deal_subject.sk_id")), bytes32(rawDealId)),
            _out(".builders.deal_subject.output")
        );
    }

    function test_nullRep() public view {
        assertEq(
            PrivacyCommitments.nullRep(bytes32(_in(".builders.null_rep.sk_id")), _in(".builders.null_rep.version")),
            _out(".builders.null_rep.output")
        );
    }

    function test_nullBond() public view {
        // note_salt is a raw keccak256 output (>= p).
        uint256 rawNoteSalt = _in(".builders.null_bond.note_salt");
        assertGt(rawNoteSalt, BN254_P);
        assertEq(
            PrivacyCommitments.nullBond(bytes32(_in(".builders.null_bond.sk_id")), bytes32(rawNoteSalt)),
            _out(".builders.null_bond.output")
        );
    }

    function test_handleCommit() public view {
        // handle_salt is a raw keccak256 output (>= p).
        uint256 rawHandleSalt = _in(".builders.handle_commit.handle_salt");
        assertGt(rawHandleSalt, BN254_P);
        assertEq(
            PrivacyCommitments.handleCommit(bytes32(_in(".builders.handle_commit.sk_id")), bytes32(rawHandleSalt)),
            _out(".builders.handle_commit.output")
        );
    }

    function test_noteBond() public view {
        // note salt again raw here (>= p).
        uint256 rawSalt = _in(".builders.note_bond.salt");
        assertGt(rawSalt, BN254_P);
        assertEq(
            PrivacyCommitments.noteBond(
                bytes32(_in(".builders.note_bond.sk_id")),
                bytes32(_in(".builders.note_bond.token")),
                _in(".builders.note_bond.amount"),
                bytes32(rawSalt)
            ),
            _out(".builders.note_bond.output")
        );
    }

    function test_lockCommit() public view {
        // deal_id and salt are raw keccak256 outputs (>= p); the first fold step is
        // dealSubject — the vectors pin the whole chain, not just the primitive.
        assertGt(_in(".builders.lock_commit.deal_id"), BN254_P);
        assertGt(_in(".builders.lock_commit.salt"), BN254_P);
        assertEq(
            PrivacyCommitments.lockCommit(
                bytes32(_in(".builders.lock_commit.sk_id")),
                bytes32(_in(".builders.lock_commit.deal_id")),
                _in(".builders.lock_commit.lock_amount"),
                bytes32(_in(".builders.lock_commit.salt"))
            ),
            _out(".builders.lock_commit.output")
        );
    }

    function test_leafRep() public view {
        // leaf salt is a raw keccak256 output (>= p); 8 fields chained in spec order.
        assertGt(_in(".builders.leaf_rep.salt"), BN254_P);
        assertEq(
            PrivacyCommitments.leafRep(
                bytes32(_in(".builders.leaf_rep.s")),
                _in(".builders.leaf_rep.count"),
                _in(".builders.leaf_rep.volume"),
                _in(".builders.leaf_rep.penalty"),
                _in(".builders.leaf_rep.in_flight"),
                bytes32(_in(".builders.leaf_rep.token")),
                bytes32(_in(".builders.leaf_rep.salt")),
                _in(".builders.leaf_rep.version")
            ),
            _out(".builders.leaf_rep.output")
        );
    }

    function test_tags_areDistinct() public pure {
        assertTrue(PrivacyCommitments.TAG_REP != PrivacyCommitments.TAG_BOND);
        assertTrue(PrivacyCommitments.TAG_BOND != PrivacyCommitments.TAG_HANDLE);
        assertTrue(PrivacyCommitments.TAG_REP != PrivacyCommitments.TAG_HANDLE);
    }

    // ---------------------------------------------------------------- tree (PoseidonTree parity)

    function test_tree_emptyRootMatches() public view {
        assertEq(uint256(tree.root()), vm.parseJsonUint(vectors, ".tree.empty_root"));
        assertTrue(tree.isKnownRoot(bytes32(vm.parseJsonUint(vectors, ".tree.empty_root"))));
    }

    function test_tree_insertRootsMatch() public {
        uint256[] memory leaves = vm.parseJsonUintArray(vectors, ".tree.leaves");
        uint256[] memory roots = vm.parseJsonUintArray(vectors, ".tree.roots");
        for (uint256 i = 0; i < leaves.length; i++) {
            (uint256 index, bytes32 newRoot) = tree.insert(bytes32(leaves[i]));
            assertEq(index, i, "index");
            assertEq(uint256(newRoot), roots[i], "root after insert");
        }
    }

    function test_tree_membershipsAreKnownRoots() public {
        // The JS twin captures the root at insert time — the historical root a witness
        // recomputes, and exactly what PoseidonTree's isKnownRoot ring must hold.
        uint256[] memory leaves = vm.parseJsonUintArray(vectors, ".tree.leaves");
        for (uint256 i = 0; i < leaves.length; i++) {
            tree.insert(bytes32(leaves[i]));
        }
        for (uint256 i = 0; i < leaves.length; i++) {
            string memory m = string.concat(".tree.memberships[", vm.toString(i), "]");
            assertTrue(tree.isKnownRoot(bytes32(vm.parseJsonUint(vectors, string.concat(m, ".root")))));
        }
    }

    function test_tree_membershipRecomputes() public view {
        // Fold each membership witness with the same poseidonT3 the tree hashes with:
        // (leaf, siblings, indices) must reproduce the historical root the JS twin recorded.
        uint256 count = vm.parseJsonUintArray(vectors, ".tree.leaves").length;
        for (uint256 i = 0; i < count; i++) {
            string memory m = string.concat(".tree.memberships[", vm.toString(i), "]");
            uint256[] memory siblings = vm.parseJsonUintArray(vectors, string.concat(m, ".siblings"));
            uint256[] memory indices = vm.parseJsonUintArray(vectors, string.concat(m, ".indices"));
            bytes32 leaf = bytes32(vm.parseJsonUint(vectors, string.concat(m, ".leaf")));
            uint256 node = uint256(leaf);
            for (uint256 level = 0; level < siblings.length; level++) {
                if (indices[level] == 0) {
                    node = uint256(PrivacyCommitments.poseidonT3(bytes32(node), bytes32(siblings[level])));
                } else {
                    node = uint256(PrivacyCommitments.poseidonT3(bytes32(siblings[level]), bytes32(node)));
                }
            }
            assertEq(node, vm.parseJsonUint(vectors, string.concat(m, ".root")), "recomputed root");
        }
    }

    // ---------------------------------------------------------------- helpers

    function _in(string memory path) private view returns (uint256) {
        return vm.parseJsonUint(vectors, path);
    }

    function _out(string memory path) private view returns (bytes32) {
        return bytes32(vm.parseJsonUint(vectors, path));
    }
}
