// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {PoseidonTree, DEFAULT_ROOT_HISTORY, MIN_ROOT_HISTORY, MAX_ROOT_HISTORY} from "../src/packages/PoseidonTree.sol";
import {PrivacyCommitments} from "../src/packages/libraries/PrivacyCommitments.sol";
import {PoseidonSingletons} from "./PoseidonSingletons.sol";

/// @title PrivacyCommitments parity tests (V0, PLURISWAP.md §3.15.3 as amended)
/// @dev The Solidity twin against test/fixtures/vectors.json — generated by `bun circuits:vectors`
///      from the JS twin, and pinned inside the Noir crate by circuits/crates/pluri_commitments
///      (`nargo test`). Three languages, one fixture: if these tests pass, on-chain Poseidon
///      (poseidon-solidity), the circuits (Noir) and the prover-side tooling (circomlibjs) agree
///      byte for byte on every commitment of the private layer.
contract PrivacyCommitmentsTest is Test {
    /// @dev The BN254 scalar field. The pinned rule: every bytes32 input is interpreted mod p.
    uint256 internal constant BN254_P = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    uint256 internal constant DEPTH = 8;

    string internal vectors;
    PoseidonTree internal tree;

    function setUp() public {
        // The private layer hashes through the pinned poseidon-solidity singletons, which a test
        // EVM starts without (PLURISWAP.md §5.1).
        PoseidonSingletons.install();
        vectors = vm.readFile("test/fixtures/vectors.json");
        tree = new PoseidonTree(uint8(DEPTH), DEFAULT_ROOT_HISTORY, address(this));
    }

    // ---------------------------------------------------------------- primitives

    function test_fixtureProvenance() public view {
        // Guards a stale fixture: the vectors must come from the canonical generator.
        assertEq(vm.parseJsonString(vectors, ".provenance.generator"), "circuits/js/vectors.ts (bun circuits:vectors)");
    }

    function test_poseidonT3_matchesVector() public view {
        // t3[0] is the circomlib poseidonperm_x5_254_3([1, 2]) vector — the same
        // constant PoseidonTree.t.sol pins — so all three twins sit on the pinned params.
        assertEq(
            PrivacyCommitments.poseidonT3(bytes32(uint256(1)), bytes32(uint256(2))), _out(".poseidon.t3[0].output")
        );
    }

    function test_poseidonT3_highEdgeMatchesVector() public view {
        uint256 a = vm.parseJsonUint(vectors, ".poseidon.t3[2].inputs[0]");
        uint256 b = vm.parseJsonUint(vectors, ".poseidon.t3[2].inputs[1]");
        // p-1 is the largest field element: the permutation must not leave the field.
        assertEq(a, BN254_P - 1);
        assertEq(PrivacyCommitments.poseidonT3(bytes32(a), bytes32(b)), _out(".poseidon.t3[2].output"));
    }

    // ---------------------------------------------------------------- builders

    function test_accountCommitment() public view {
        bytes32 skId = bytes32(_in(".builders.s.sk_id"));
        assertEq(PrivacyCommitments.accountCommitment(skId), _out(".builders.s.output"));
    }

    function test_hn() public view {
        // registry_id is a raw keccak256 output (>= p): the mod-p rule is pinned here.
        uint256 rawRegistryId = _in(".builders.hn.registry_id");
        assertGt(rawRegistryId, BN254_P);
        assertEq(
            PrivacyCommitments.hn(bytes32(_in(".builders.hn.anchor")), bytes32(rawRegistryId)),
            _out(".builders.hn.output")
        );
    }

    function test_dealSubject() public view {
        // deal_id is a raw keccak256 output (>= p): the mod-p rule is pinned here too.
        uint256 rawDealId = _in(".builders.deal_subject.deal_id");
        assertGt(rawDealId, BN254_P);
        assertEq(
            PrivacyCommitments.dealSubject(bytes32(_in(".builders.deal_subject.sk_id")), bytes32(rawDealId)),
            _out(".builders.deal_subject.output")
        );
    }

    function test_nullRep() public view {
        assertEq(
            PrivacyCommitments.nullRep(bytes32(_in(".builders.null_rep.sk_id")), _in(".builders.null_rep.version")),
            _out(".builders.null_rep.output")
        );
    }

    function test_nullBond() public view {
        // note_salt is a raw keccak256 output (>= p).
        uint256 rawNoteSalt = _in(".builders.null_bond.note_salt");
        assertGt(rawNoteSalt, BN254_P);
        assertEq(
            PrivacyCommitments.nullBond(bytes32(_in(".builders.null_bond.sk_id")), bytes32(rawNoteSalt)),
            _out(".builders.null_bond.output")
        );
    }

    /// The account leaf's salt is DERIVED, which is what makes an account recoverable from `sk_id`
    /// alone (§3.15.3). Pinned in the fourth language like every other builder.
    function test_leafSalt() public view {
        assertEq(
            PrivacyCommitments.leafSalt(bytes32(_in(".builders.leaf_salt.sk_id")), _in(".builders.leaf_salt.version")),
            _out(".builders.leaf_salt.output")
        );
    }

    /// The property the derivation exists for: with the secret and the stats, the leaf comes back.
    /// Nothing else is needed -- no stored salt, no local database. Losing that database used to
    /// cost the whole account: reputation, tiers, and the bonds gated behind `claimed`.
    function test_aLeafIsRebuiltFromTheSecretAlone() public view {
        bytes32 skId = bytes32(_in(".prepare.sk_id"));
        bytes32 s = PrivacyCommitments.accountCommitment(skId);
        // The genesis leaf the registry sample registered: all counters zero, version zero.
        assertEq(
            PrivacyCommitments.leafRep(
                s,
                0,
                0,
                0,
                0,
                bytes32(0),
                PrivacyCommitments.leafSalt(skId, 0),
                0,
                _out(".prepare.cp_root"), // an empty counterparty tree: a new account has met nobody
                0,
                0
            ),
            _out(".registry.sample_leaf0")
        );
        // And the leaf the admission transition writes: the principal in flight, version one.
        assertEq(
            PrivacyCommitments.leafRep(
                s,
                0,
                0,
                0,
                _in(".prepare.principal"),
                bytes32(_in(".prepare.token")),
                PrivacyCommitments.leafSalt(skId, 1),
                1,
                _out(".prepare.cp_root"), // carried through: an admission decides no credit
                0,
                0
            ),
            _out(".prepare.new_leaf")
        );
    }

    /// The vault's salts are DERIVED too (2026-09-23), and for a heavier reason than the leaf's: a
    /// note holds TOKENS and its salt is what spends it. Pinned in the fourth language, both of them.
    function test_noteSalt() public view {
        assertEq(
            PrivacyCommitments.noteSalt(
                bytes32(_in(".builders.note_salt.sk_id")), bytes32(_in(".builders.note_salt.seed"))
            ),
            _out(".builders.note_salt.output")
        );
    }

    function test_lockSalt() public view {
        uint256 rawDealId = _in(".builders.lock_salt.deal_id");
        assertGt(rawDealId, BN254_P);
        assertEq(
            PrivacyCommitments.lockSalt(bytes32(_in(".builders.lock_salt.sk_id")), bytes32(rawDealId)),
            _out(".builders.lock_salt.output")
        );
    }

    /// The vault's own version of the property above: with the secret and what the chain states,
    /// every note of the committed lifecycle comes back. A note's salt derives from whatever the
    /// note came from -- a deposit index, or the nullifier of the note or lock it was carved out of
    /// -- and every amount is public somewhere, so the walk needs nothing kept on the side.
    function test_aVaultIsRebuiltFromTheSecretAlone() public view {
        bytes32 skId = bytes32(_in(".deposit.sk_id"));
        bytes32 token = bytes32(_in(".deposit.token"));

        // The deposit: the one note with no parent, seeded by the account's deposit index.
        bytes32 depositSalt = PrivacyCommitments.noteSalt(skId, bytes32(_in(".deposit.index")));
        assertEq(PrivacyCommitments.noteBond(skId, token, _in(".deposit.amount"), depositSalt), _out(".deposit.note"));

        // The split: the earmark from the deal it belongs to, the change from the parent's burn.
        bytes32 lockSalt = PrivacyCommitments.lockSalt(skId, bytes32(_in(".bond.deal_id")));
        assertEq(
            PrivacyCommitments.lockCommit(skId, bytes32(_in(".bond.deal_id")), _in(".bond.lock_amount"), lockSalt),
            _out(".bond.lock_commit")
        );
        bytes32 burn = PrivacyCommitments.nullBond(skId, depositSalt);
        assertEq(burn, _out(".bond.null_bond"));
        assertEq(
            PrivacyCommitments.noteBond(
                skId, token, _in(".deposit.amount") - _in(".bond.lock_amount"), PrivacyCommitments.noteSalt(skId, burn)
            ),
            _out(".bond.change_note")
        );

        // The reabsorb: the released lock merges back, seeded by the lock's own burn.
        bytes32 lockBurn = PrivacyCommitments.nullBond(skId, lockSalt);
        assertEq(lockBurn, _out(".reabsorb.null_bond"));
        assertEq(
            PrivacyCommitments.noteBond(
                skId, token, _in(".reabsorb.amount"), PrivacyCommitments.noteSalt(skId, lockBurn)
            ),
            _out(".reabsorb.new_note")
        );

        // The withdraw: the change of the change, seeded by the change note's burn.
        bytes32 changeBurn = PrivacyCommitments.nullBond(skId, bytes32(_in(".bond.change_salt")));
        assertEq(changeBurn, _out(".withdraw.null_bond"));
        assertEq(
            PrivacyCommitments.noteBond(
                skId,
                token,
                _in(".bond.note_amount") - _in(".bond.lock_amount") - _in(".withdraw.amount"),
                PrivacyCommitments.noteSalt(skId, changeBurn)
            ),
            _out(".withdraw.change_note")
        );
    }

    function test_handleCommit() public view {
        // handle_salt is a raw keccak256 output (>= p).
        uint256 rawHandleSalt = _in(".builders.handle_commit.handle_salt");
        assertGt(rawHandleSalt, BN254_P);
        assertEq(
            PrivacyCommitments.handleCommit(bytes32(_in(".builders.handle_commit.sk_id")), bytes32(rawHandleSalt)),
            _out(".builders.handle_commit.output")
        );
    }

    function test_noteBond() public view {
        // note salt again raw here (>= p).
        uint256 rawSalt = _in(".builders.note_bond.salt");
        assertGt(rawSalt, BN254_P);
        assertEq(
            PrivacyCommitments.noteBond(
                bytes32(_in(".builders.note_bond.sk_id")),
                bytes32(_in(".builders.note_bond.token")),
                _in(".builders.note_bond.amount"),
                bytes32(rawSalt)
            ),
            _out(".builders.note_bond.output")
        );
    }

    function test_lockCommit() public view {
        // deal_id and salt are raw keccak256 outputs (>= p); the first fold step is
        // dealSubject — the vectors pin the whole chain, not just the primitive.
        assertGt(_in(".builders.lock_commit.deal_id"), BN254_P);
        assertGt(_in(".builders.lock_commit.salt"), BN254_P);
        assertEq(
            PrivacyCommitments.lockCommit(
                bytes32(_in(".builders.lock_commit.sk_id")),
                bytes32(_in(".builders.lock_commit.deal_id")),
                _in(".builders.lock_commit.lock_amount"),
                bytes32(_in(".builders.lock_commit.salt"))
            ),
            _out(".builders.lock_commit.output")
        );
    }

    function test_leafRep() public view {
        // leaf salt is a raw keccak256 output (>= p); 11 fields chained in spec order.
        assertGt(_in(".builders.leaf_rep.salt"), BN254_P);
        assertEq(
            PrivacyCommitments.leafRep(
                bytes32(_in(".builders.leaf_rep.s")),
                _in(".builders.leaf_rep.count"),
                _in(".builders.leaf_rep.volume"),
                _in(".builders.leaf_rep.penalty"),
                _in(".builders.leaf_rep.in_flight"),
                bytes32(_in(".builders.leaf_rep.token")),
                bytes32(_in(".builders.leaf_rep.salt")),
                _in(".builders.leaf_rep.version"),
                bytes32(_in(".builders.leaf_rep.cp_root")),
                _in(".builders.leaf_rep.epoch"),
                _in(".builders.leaf_rep.epoch_credits")
            ),
            _out(".builders.leaf_rep.output")
        );
    }

    /// The commutative pair of §3.14.7: the two sides of a deal reach the same name without agreeing
    /// on an order, which is what lets each of them prove it with only its own secret.
    function test_pairId_isUnordered() public view {
        bytes32 a = bytes32(_in(".builders.pair_id.s_a"));
        bytes32 b = bytes32(_in(".builders.pair_id.s_b"));
        assertEq(PrivacyCommitments.pairId(a, b), _out(".builders.pair_id.output"));
        assertEq(PrivacyCommitments.pairId(b, a), _out(".builders.pair_id.swapped"));
        assertEq(PrivacyCommitments.pairId(a, b), PrivacyCommitments.pairId(b, a));
    }

    function test_pairTag_bindsTheDeal() public view {
        bytes32 a = bytes32(_in(".builders.pair_id.s_a"));
        bytes32 b = bytes32(_in(".builders.pair_id.s_b"));
        bytes32 dealId = bytes32(_in(".builders.pair_tag.deal_id"));
        assertEq(PrivacyCommitments.pairTag(a, b, dealId), _out(".builders.pair_tag.output"));
        // Blinded per deal: the same pair in another deal is another tag, so the tag published on
        // chain never links two of their deals together.
        assertTrue(PrivacyCommitments.pairTag(a, b, dealId) != PrivacyCommitments.pairTag(a, b, bytes32(uint256(1))));
    }

    function test_tags_areDistinct() public pure {
        // Every tag against every other: the domains only stay apart while this holds, and the
        // derived salts lean on it -- a note's salt and the nullifier taken over that salt are two
        // tags of the same fold, which is what lets a child be seeded by its parent's burn.
        uint256[6] memory tags = [
            PrivacyCommitments.TAG_REP,
            PrivacyCommitments.TAG_BOND,
            PrivacyCommitments.TAG_HANDLE,
            PrivacyCommitments.TAG_LEAF,
            PrivacyCommitments.TAG_NOTE,
            PrivacyCommitments.TAG_LOCK
        ];
        for (uint256 i = 0; i < tags.length; i++) {
            for (uint256 j = i + 1; j < tags.length; j++) {
                assertTrue(tags[i] != tags[j], "tags collide");
            }
        }
    }

    // ---------------------------------------------------------------- tree (PoseidonTree parity)

    function test_tree_emptyRootMatches() public view {
        assertEq(uint256(tree.root()), vm.parseJsonUint(vectors, ".tree.empty_root"));
        assertTrue(tree.isKnownRoot(bytes32(vm.parseJsonUint(vectors, ".tree.empty_root"))));
    }

    function test_tree_insertRootsMatch() public {
        uint256[] memory leaves = vm.parseJsonUintArray(vectors, ".tree.leaves");
        uint256[] memory roots = vm.parseJsonUintArray(vectors, ".tree.roots");
        for (uint256 i = 0; i < leaves.length; i++) {
            (uint256 index, bytes32 newRoot) = tree.insert(bytes32(leaves[i]));
            assertEq(index, i, "index");
            assertEq(uint256(newRoot), roots[i], "root after insert");
        }
    }

    function test_tree_membershipsAreKnownRoots() public {
        // The JS twin captures the root at insert time — the historical root a witness
        // recomputes, and exactly what PoseidonTree's isKnownRoot ring must hold.
        uint256[] memory leaves = vm.parseJsonUintArray(vectors, ".tree.leaves");
        for (uint256 i = 0; i < leaves.length; i++) {
            tree.insert(bytes32(leaves[i]));
        }
        for (uint256 i = 0; i < leaves.length; i++) {
            string memory m = string.concat(".tree.memberships[", vm.toString(i), "]");
            assertTrue(tree.isKnownRoot(bytes32(vm.parseJsonUint(vectors, string.concat(m, ".root")))));
        }
    }

    function test_tree_membershipRecomputes() public view {
        // Fold each membership witness with the same poseidonT3 the tree hashes with:
        // (leaf, siblings, indices) must reproduce the historical root the JS twin recorded.
        uint256 count = vm.parseJsonUintArray(vectors, ".tree.leaves").length;
        for (uint256 i = 0; i < count; i++) {
            string memory m = string.concat(".tree.memberships[", vm.toString(i), "]");
            uint256[] memory siblings = vm.parseJsonUintArray(vectors, string.concat(m, ".siblings"));
            uint256[] memory indices = vm.parseJsonUintArray(vectors, string.concat(m, ".indices"));
            bytes32 leaf = bytes32(vm.parseJsonUint(vectors, string.concat(m, ".leaf")));
            uint256 node = uint256(leaf);
            for (uint256 level = 0; level < siblings.length; level++) {
                if (indices[level] == 0) {
                    node = uint256(PrivacyCommitments.poseidonT3(bytes32(node), bytes32(siblings[level])));
                } else {
                    node = uint256(PrivacyCommitments.poseidonT3(bytes32(siblings[level]), bytes32(node)));
                }
            }
            assertEq(node, vm.parseJsonUint(vectors, string.concat(m, ".root")), "recomputed root");
        }
    }

    // ---------------------------------------------------------------- helpers

    function _in(string memory path) private view returns (uint256) {
        return vm.parseJsonUint(vectors, path);
    }

    function _out(string memory path) private view returns (bytes32) {
        return bytes32(vm.parseJsonUint(vectors, path));
    }
}
