// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {PassportDecoderMock} from "../mocks/PassportDecoderMock.sol";
import {BundleVerifierMock} from "../mocks/BundleVerifierMock.sol";
import {ClaimVerifierMock} from "../mocks/ClaimVerifierMock.sol";
import {HumanityRegistry} from "../src/packages/HumanityRegistry.sol";
import {RegistryHumanityVerifier} from "../src/packages/adapters/RegistryHumanityVerifier.sol";
import {RegistryAccountVerifier} from "../src/packages/adapters/RegistryAccountVerifier.sol";
import {PrivatePassport} from "../src/packages/PrivatePassport.sol";
import {PrivateReputation} from "../src/packages/PrivateReputation.sol";
import {PoseidonTree, DEFAULT_ROOT_HISTORY, MIN_ROOT_HISTORY, MAX_ROOT_HISTORY} from "../src/packages/PoseidonTree.sol";
import {PoseidonSingletons} from "./PoseidonSingletons.sol";

/// @title Register with real proofs (V1, PLURISWAP.md §3.15.3 "Registro", §3.15.9)
/// @dev The register bundle behind the REAL ultra_honk verifiers: the committed fixtures
///      (test/fixtures/proofs/, generated by `bun circuits:prove` with the pinned toolchain)
///      are verified on-chain by the adapter-deployed Honk contracts. This is the first
///      interface pair (IHumanityVerifier, IAccountVerifier) whose mock is gone — until V2/V3
///      replace theirs, those remain mocks and are marked as such.
contract RegisterRealProofTest is Test {
    BundleVerifierMock internal bundle;
    address internal constant FEE_TO = address(0xFEE);

    string internal vectors;
    string internal proofHumanity;
    string internal proofAccount;

    PassportDecoderMock internal decoder;
    HumanityRegistry internal registry;
    RegistryHumanityVerifier internal humanityVerifier;
    RegistryAccountVerifier internal accountVerifier;
    address internal anchor;

    PoseidonTree internal accountTree;
    PrivatePassport internal passport;
    PrivateReputation internal reputation;

    bytes32 internal hsk;
    bytes32 internal hn;
    bytes32 internal leaf0;

    function setUp() public {
        bundle = new BundleVerifierMock();
        // The private layer hashes through the pinned poseidon-solidity singletons, which a test
        // EVM starts without (PLURISWAP.md §5.1).
        PoseidonSingletons.install();
        vectors = vm.readFile("test/fixtures/vectors.json");
        proofHumanity = vm.readFile("test/fixtures/proofs/register_humanity.json");
        proofAccount = vm.readFile("test/fixtures/proofs/register_account.json");

        hsk = bytes32(vm.parseJsonUint(vectors, ".registry.hsk"));
        hn = bytes32(vm.parseJsonUint(vectors, ".registry.sample_hn"));
        leaf0 = bytes32(vm.parseJsonUint(vectors, ".registry.sample_leaf0"));

        decoder = new PassportDecoderMock(200_000, 1 days);
        anchor = makeAddr("anchor");
        decoder.setScore(anchor, 200_000, uint64(block.timestamp + 30 days));
        registry = new HumanityRegistry(decoder, 0, bytes32(vm.parseJsonUint(vectors, ".registry.registry_id")));

        bytes32 commitment = registry.identityCommitmentOf(hsk);
        assertEq(commitment, bytes32(vm.parseJsonUint(vectors, ".registry.identity_commitment")));
        vm.prank(anchor);
        registry.enroll(commitment);

        humanityVerifier = new RegistryHumanityVerifier(
            registry, vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/register_humanity.json"), ".initcode")
        );
        accountVerifier = new RegistryAccountVerifier(
            registry, vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/register_account.json"), ".initcode")
        );

        // Every remaining mock is pre-deployed BEFORE the prediction: an inline `new Mock()`
        // inside a constructor-argument list consumes a CREATE nonce of this test contract
        // and would drift the predicted address (the tree's owner must be the reputation).
        ClaimVerifierMock claimProof = new ClaimVerifierMock(); // V3 replaces this

        // The accounts tree is wired into the passport before its owner exists: the predicted
        // CREATE address pattern of PrivateRegister.t.sol (tree, passport, reputation).
        address predictedRep = vm.computeCreateAddress(address(this), vm.getNonce(address(this)) + 2);
        accountTree = new PoseidonTree(32, DEFAULT_ROOT_HISTORY, predictedRep);
        passport = new PrivatePassport(accountTree, humanityVerifier, bundle);
        reputation = new PrivateReputation(
            passport, accountTree, accountVerifier, bundle, claimProof, FEE_TO, 0, 0, 0, 0, address(this), address(0)
        );
        assertEq(address(reputation), predictedRep, "predicted tree owner drifted");
    }

    function proofHumanityBlob() internal view returns (bytes memory) {
        return vm.parseJsonBytes(proofHumanity, ".proof_with_public_inputs");
    }

    function proofAccountBlob() internal view returns (bytes memory) {
        return vm.parseJsonBytes(proofAccount, ".proof_with_public_inputs");
    }

    // ---------------------------------------------------------------- the bundle, green path

    function test_register_bundleWithRealProofs() public {
        vm.expectEmit(true, true, true, true, address(passport));
        emit PrivatePassport.HumanityRegistered(hn);
        passport.register(proofHumanityBlob(), hn);

        vm.expectEmit(true, true, true, true, address(reputation));
        emit PrivateReputation.AccountRegistered(hn, leaf0, 0);
        reputation.register(proofAccountBlob(), hn, leaf0);

        assertTrue(passport.humanitySpent(hn));
        assertTrue(reputation.registeredHn(hn));

        // Replay dies on both sides of the bundle, exactly as with the mocks (F1):
        // one human (one hn) = one account, forever.
        vm.expectRevert(PrivatePassport.HumanAlreadySpent.selector);
        passport.register(proofHumanityBlob(), hn);
        vm.expectRevert(PrivateReputation.AlreadyRegistered.selector);
        reputation.register(proofAccountBlob(), hn, leaf0);
    }

    function test_register_leaf0_isTheCircuitsLeaf() public view {
        // The adapters see exactly the (hn, leaf0) the circuits proved: the split of the blob
        // matches the arguments the modules pass. A mismatched argument reads as false —
        // the green path of the bundle test is what pins this.
        assertTrue(humanityVerifier.verifyHumanity(proofHumanityBlob(), hn));
        assertTrue(accountVerifier.verifyAccount(proofAccountBlob(), hn, leaf0));
    }

    // ---------------------------------------------------------------- gas of the real verify

    function test_verify_gas() public {
        // The blobs are read BEFORE the window: building one goes through a file-reading cheatcode,
        // and a cheatcode inside the measurement is the measurement — it was reading as ~1.1M of
        // verifier gas the verifier never spent (2026-09-23).
        bytes memory humanityBlob = proofHumanityBlob();
        bytes memory accountBlob = proofAccountBlob();

        uint256 before = gasleft();
        humanityVerifier.verifyHumanity(humanityBlob, hn);
        uint256 humanityCost = before - gasleft();

        before = gasleft();
        accountVerifier.verifyAccount(accountBlob, hn, leaf0);
        uint256 accountCost = before - gasleft();

        emit log_named_uint("verifyHumanity gas", humanityCost);
        emit log_named_uint("verifyAccount gas", accountCost);
    }

    // ---------------------------------------------------------------- fail closed

    function test_verifyHumanity_rejectsTamperedProof() public {
        bytes memory blob = proofHumanityBlob();
        blob[42] = blob[42] ^ 0xff; // one byte inside the proof body
        assertFalse(humanityVerifier.verifyHumanity(blob, hn));
        assertFalse(accountVerifier.verifyAccount(blob, hn, leaf0));

        vm.expectRevert(PrivatePassport.HumanityNotVerified.selector);
        passport.register(blob, hn);
    }

    function test_verify_rejectsWrongHn() public {
        bytes32 wrongHn = bytes32(uint256(keccak256("not-the-hn")));
        assertFalse(humanityVerifier.verifyHumanity(proofHumanityBlob(), wrongHn));
        assertFalse(accountVerifier.verifyAccount(proofAccountBlob(), wrongHn, leaf0));

        vm.expectRevert(PrivatePassport.HumanityNotVerified.selector);
        passport.register(proofHumanityBlob(), wrongHn);
    }

    function test_verify_rejectsWrongLeaf0() public {
        bytes32 wrongLeaf = bytes32(uint256(0xBEEF));
        assertFalse(accountVerifier.verifyAccount(proofAccountBlob(), hn, wrongLeaf));

        // Burn the humanity first: the reputation checks humanitySpent BEFORE the account
        // proof, and the meaningful failure here is the proof's, not the bundle order's.
        passport.register(proofHumanityBlob(), hn);
        vm.expectRevert(PrivateReputation.AccountNotVerified.selector);
        reputation.register(proofAccountBlob(), hn, wrongLeaf);
    }

    function test_verify_rejectsMalformedBlob() public {
        // Short blobs and truncated public-input sections read as false, never revert-shaped.
        assertFalse(humanityVerifier.verifyHumanity(hex"0011", hn));
        assertFalse(humanityVerifier.verifyHumanity(_truncate(proofHumanityBlob(), 64), hn));
        assertFalse(accountVerifier.verifyAccount(hex"0011", hn, leaf0));
        assertFalse(accountVerifier.verifyAccount(_truncate(proofAccountBlob(), 64), hn, leaf0));
    }

    function test_verifyHumanity_rejectsForeignRegistryRoot() public {
        // Same proof, but an adapter serving an EMPTY registry: the enrollment root the
        // proof names was never known there — the amplification check fails closed. This is
        // the registry-model trust boundary: a proof only pays inside the registry it names.
        HumanityRegistry foreign =
            new HumanityRegistry(decoder, 0, bytes32(vm.parseJsonUint(vectors, ".registry.registry_id")));
        RegistryHumanityVerifier foreignVerifier = new RegistryHumanityVerifier(
            foreign, vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/register_humanity.json"), ".initcode")
        );
        assertFalse(foreignVerifier.verifyHumanity(proofHumanityBlob(), hn));
    }

    function test_verify_rejectsForeignRegistryDomain() public {
        // A proof naming another registry's domain cannot verify against this one, even with
        // a matching tree: the domain is the registry's identity, pinned by the adapter.
        HumanityRegistry otherDomain = new HumanityRegistry(decoder, 0, bytes32(uint256(keccak256("other"))));
        RegistryHumanityVerifier otherVerifier = new RegistryHumanityVerifier(
            otherDomain, vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/register_humanity.json"), ".initcode")
        );
        assertFalse(otherVerifier.verifyHumanity(proofHumanityBlob(), hn));
    }

    function test_verify_rejectsCrossCircuitProofs() public {
        // The humanity blob splits as (hn, root, domain); the account blob as (hn, leaf0,
        // domain). Swapping them must read as false on both sides: the account blob's
        // "root" is really leaf0, which no registry tree ever knew — and vice versa.
        assertFalse(humanityVerifier.verifyHumanity(proofAccountBlob(), hn));
        assertFalse(accountVerifier.verifyAccount(proofHumanityBlob(), hn, leaf0));
    }

    /// @dev Solidity cannot slice memory bytes; the truncated-blob tests need copies.
    function _truncate(bytes memory b, uint256 n) internal pure returns (bytes memory) {
        bytes memory out = new bytes(n);
        for (uint256 i = 0; i < n; i++) {
            out[i] = b[i];
        }
        return out;
    }

    function test_register_account_needsHumanityFirst() public {
        // The bundle order is the security property: the reputation only trusts an hn the
        // passport has burned against its own membership proof.
        vm.expectRevert(PrivateReputation.HumanityNotProven.selector);
        reputation.register(proofAccountBlob(), hn, leaf0);
    }
}
