// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {TestToken} from "../mocks/TestToken.sol";
import {PassportDecoderMock} from "../mocks/PassportDecoderMock.sol";
import {HumanityRegistry} from "../src/packages/HumanityRegistry.sol";
import {IReputation} from "../src/packages/interfaces/IReputation.sol";
import {RegistryHumanityVerifier} from "../src/packages/adapters/RegistryHumanityVerifier.sol";
import {RegistryAccountVerifier} from "../src/packages/adapters/RegistryAccountVerifier.sol";
import {PreparePassportVerifier} from "../src/packages/adapters/PreparePassportVerifier.sol";
import {PrepareAdmitVerifier} from "../src/packages/adapters/PrepareAdmitVerifier.sol";
import {ClaimVerifier} from "../src/packages/adapters/ClaimVerifier.sol";
import {DepositVerifier} from "../src/packages/adapters/DepositVerifier.sol";
import {PrepareBondVerifier} from "../src/packages/adapters/PrepareBondVerifier.sol";
import {ReabsorbVerifier} from "../src/packages/adapters/ReabsorbVerifier.sol";
import {WithdrawVerifier} from "../src/packages/adapters/WithdrawVerifier.sol";
import {PrivatePassport} from "../src/packages/PrivatePassport.sol";
import {PrivateReputation} from "../src/packages/PrivateReputation.sol";
import {PrivateBondVault} from "../src/packages/PrivateBondVault.sol";
import {PoseidonTree, DEFAULT_ROOT_HISTORY, MIN_ROOT_HISTORY, MAX_ROOT_HISTORY} from "../src/packages/PoseidonTree.sol";
import {PoseidonSingletons} from "./PoseidonSingletons.sol";

/// @title The whole private lifecycle on real proofs (V3, PLURISWAP.md §3.15.4-§3.15.6, §3.15.9)
/// @dev One deal, two trees, every proof real: register (V1's proofs) puts the genesis leaf
///      in the account tree, deposit (V3) puts the source note in the vault's notes tree,
///      the activation bundle runs the THREE prepares with real proofs in one tx —
///      passport, bond split, admission — then admit, reserve, the terminal delta, and the
///      notes' way home: unlock, reabsorb, withdraw. The five V3 verifiers
///      (IDepositVerifier, IPrepareBondVerifier, IClaimVerifier, IReabsorbVerifier,
///      IWithdrawVerifier) are the real adapters over committed Honk initcode — after this,
///      no verifier mock remains anywhere in the wiring.
///
///      The fixture story (test/fixtures/vectors.json, generated by `bun circuits:vectors`)
///      and the chain agree by construction: the vault's self-deployed depth-20 notes tree
///      receives exactly the fixture's inserts in the fixture's order (deposit's note,
///      split's change note, reabsorb's merged note, withdraw's second change note), and
///      the depth-32 account tree the prepare/claim story's (leaf0, prepare's leaf, delta
///      leaf). The withdraw proof witnesses the change note's own insert-time root — any
///      root of the ring buffer is a valid witness; the nullifier decides the replay.
///
///      The pinned token is a synthetic address: a full OZ ERC20 runtime (TestToken, 6
///      decimals) is etched there so the vault can actually pull and push — the proofs'
///      token pub is that address, and its `decimals()` answers 6 for the admission
///      adapter's live read.
contract VaultRealProofTest is Test {

    /// @dev The §3.14.7 pair tag. With a mock verifier nothing checks its VALUE — what these tests
    ///      exercise is that both sides of one activation carry the SAME one, which is what the module
    ///      compares. The real value is pinned by the fixture tests and by the circuit itself.
    /// @dev The REAL pair tag and epoch of the pinned sample: this suite runs against committed
    ///      proofs, so both have to be the values the circuit committed to.
    function pairTag() internal view returns (bytes32) {
        return bytes32(vm.parseJsonUint(vectors, ".prepare.pair_tag"));
    }

    function claimEpoch() internal view returns (uint256) {
        return vm.parseJsonUint(vectors, ".claim.claim_epoch");
    }

    /// @dev A fresh deal id / counterparty per call: these tests predate the 2026-09-23 rule that credit
    ///      is once per counterparty, and they all mean "another deal with somebody new". The ones that
    ///      mean "the same somebody again" say so by passing a fixed tag.
    uint256 private _tagNonce;

    function _dealTag() internal returns (bytes32) {
        return keccak256(abi.encode("deal", ++_tagNonce));
    }

    function _cpTag() internal returns (bytes32) {
        return keccak256(abi.encode("counterparty", ++_tagNonce));
    }
    uint256 internal constant WALLET_KEY = 0xA11CE;

    string internal vectors;
    string internal proofHumanity;
    string internal proofAccount;
    string internal proofPassport;
    string internal proofAdmit;
    string internal proofDeposit;
    string internal proofBond;
    string internal proofClaim;
    string internal proofReabsorb;
    string internal proofWithdraw;

    HumanityRegistry internal registry;
    RegistryHumanityVerifier internal humanityVerifier;
    RegistryAccountVerifier internal accountVerifier;
    PreparePassportVerifier internal passportVerifier;
    PrepareAdmitVerifier internal admitVerifier;
    ClaimVerifier internal claimVerifier;
    DepositVerifier internal depositVerifier;
    PrepareBondVerifier internal bondVerifier;
    ReabsorbVerifier internal reabsorbVerifier;
    WithdrawVerifier internal withdrawVerifier;
    address internal anchor;
    address internal wallet;
    address internal operator;

    PoseidonTree internal accountTree;
    PrivatePassport internal passport;
    PrivateReputation internal reputation;
    PrivateBondVault internal vault;
    address internal sink;

    bytes32 internal hn;
    bytes32 internal leaf0;
    bytes32 internal dealId;
    bytes32 internal dealSubject;
    bytes32 internal repRoot;
    bytes32 internal newLeaf;
    bytes32 internal nullRep0;
    address internal token;
    uint256 internal depositAmount;
    bytes32 internal depositNote;
    bytes32 internal lockCommit;
    bytes32 internal changeNote;
    bytes32 internal nullBondNote;
    bytes32 internal bondRoot0;
    uint256 internal lockAmount;
    bytes32 internal claimNewLeaf;
    bytes32 internal nullRep1;
    bytes32 internal claimRoot;
    bytes32 internal reabsorbNote;
    bytes32 internal reabsorbNull;
    address internal withdrawDest;
    uint256 internal withdrawAmount;
    bytes32 internal withdrawChangeNote;
    bytes32 internal withdrawNull;
    bytes32 internal withdrawRoot;
    uint256 internal principal;
    uint256 internal deadline;

    function setUp() public {
        // The private layer hashes through the pinned poseidon-solidity singletons, which a test
        // EVM starts without (PLURISWAP.md §5.1).
        PoseidonSingletons.install();
        // forge's chain starts at timestamp 1: warp to a realistic clock so deadlines
        // carry meaning (the V1 lesson).
        vm.warp(1_700_000_000);
        deadline = block.timestamp + 2 hours;

        vectors = vm.readFile("test/fixtures/vectors.json");
        proofHumanity = vm.readFile("test/fixtures/proofs/register_humanity.json");
        proofAccount = vm.readFile("test/fixtures/proofs/register_account.json");
        proofPassport = vm.readFile("test/fixtures/proofs/prepare_passport.json");
        proofAdmit = vm.readFile("test/fixtures/proofs/prepare_admit.json");
        proofDeposit = vm.readFile("test/fixtures/proofs/deposit.json");
        proofBond = vm.readFile("test/fixtures/proofs/prepare_bond.json");
        proofClaim = vm.readFile("test/fixtures/proofs/claim.json");
        proofReabsorb = vm.readFile("test/fixtures/proofs/reabsorb.json");
        proofWithdraw = vm.readFile("test/fixtures/proofs/withdraw.json");

        hn = bytes32(vm.parseJsonUint(vectors, ".registry.sample_hn"));
        leaf0 = bytes32(vm.parseJsonUint(vectors, ".registry.sample_leaf0"));
        dealId = bytes32(vm.parseJsonUint(vectors, ".bond.deal_id"));
        dealSubject = bytes32(vm.parseJsonUint(vectors, ".bond.deal_subject"));
        repRoot = bytes32(vm.parseJsonUint(vectors, ".prepare.root"));
        newLeaf = bytes32(vm.parseJsonUint(vectors, ".prepare.new_leaf"));
        nullRep0 = bytes32(vm.parseJsonUint(vectors, ".prepare.null_rep"));
        token = address(uint160(vm.parseJsonUint(vectors, ".deposit.token")));
        depositAmount = vm.parseJsonUint(vectors, ".deposit.amount");
        depositNote = bytes32(vm.parseJsonUint(vectors, ".deposit.note"));
        lockAmount = vm.parseJsonUint(vectors, ".bond.lock_amount");
        lockCommit = bytes32(vm.parseJsonUint(vectors, ".bond.lock_commit"));
        changeNote = bytes32(vm.parseJsonUint(vectors, ".bond.change_note"));
        nullBondNote = bytes32(vm.parseJsonUint(vectors, ".bond.null_bond"));
        bondRoot0 = bytes32(vm.parseJsonUint(vectors, ".bond.root"));
        claimNewLeaf = bytes32(vm.parseJsonUint(vectors, ".claim.new_leaf"));
        nullRep1 = bytes32(vm.parseJsonUint(vectors, ".claim.null_rep"));
        claimRoot = bytes32(vm.parseJsonUint(vectors, ".claim.root"));
        reabsorbNote = bytes32(vm.parseJsonUint(vectors, ".reabsorb.new_note"));
        reabsorbNull = bytes32(vm.parseJsonUint(vectors, ".reabsorb.null_bond"));
        withdrawDest = address(uint160(vm.parseJsonUint(vectors, ".withdraw.dest")));
        withdrawAmount = vm.parseJsonUint(vectors, ".withdraw.amount");
        withdrawChangeNote = bytes32(vm.parseJsonUint(vectors, ".withdraw.change_note"));
        withdrawNull = bytes32(vm.parseJsonUint(vectors, ".withdraw.null_bond"));
        withdrawRoot = bytes32(vm.parseJsonUint(vectors, ".withdraw.root"));
        principal = vm.parseJsonUint(vectors, ".claim.principal");

        // The pinned token is synthetic: etch a full OZ ERC20 runtime there so the vault
        // can pull (deposit) and push (withdraw) for real — and so the admission adapter's
        // live `decimals()` read answers the proof's 6.
        vm.etch(token, type(TestToken).runtimeCode);

        // The registry of V1 (the humanity proofs still witness its tree).
        PassportDecoderMock decoder = new PassportDecoderMock(200_000, 1 days);
        anchor = makeAddr("anchor");
        decoder.setScore(anchor, 200_000, uint64(block.timestamp + 30 days));
        registry = new HumanityRegistry(decoder, 0, bytes32(vm.parseJsonUint(vectors, ".registry.registry_id")));
        bytes32 commitment = registry.identityCommitmentOf(bytes32(vm.parseJsonUint(vectors, ".registry.hsk")));
        vm.prank(anchor);
        registry.enroll(commitment);

        // The nine real verifiers, from committed initcode (the adapters deploy the
        // generated Honk contracts; nothing in the main build links them).
        humanityVerifier = new RegistryHumanityVerifier(
            registry, vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/register_humanity.json"), ".initcode")
        );
        accountVerifier = new RegistryAccountVerifier(
            registry, vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/register_account.json"), ".initcode")
        );
        passportVerifier = new PreparePassportVerifier(
            vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/prepare_passport.json"), ".initcode")
        );
        admitVerifier = new PrepareAdmitVerifier(
            vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/prepare_admit.json"), ".initcode")
        );
        claimVerifier =
            new ClaimVerifier(vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/claim.json"), ".initcode"));
        depositVerifier =
            new DepositVerifier(vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/deposit.json"), ".initcode"));
        bondVerifier = new PrepareBondVerifier(
            vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/prepare_bond.json"), ".initcode")
        );
        reabsorbVerifier =
            new ReabsorbVerifier(vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/reabsorb.json"), ".initcode"));
        withdrawVerifier =
            new WithdrawVerifier(vm.parseJsonBytes(vm.readFile("test/fixtures/verifiers/withdraw.json"), ".initcode"));

        // The wiring circle, broken by CREATE prediction: the tree's owner is the
        // reputation (predicted), the reputation's bound vault is the vault (predicted) —
        // both predictions from THIS contract's nonce, every constructor-argument `new`
        // already done above so the count cannot drift.
        operator = address(this);
        sink = makeAddr("sink");
        uint256 nonce = vm.getNonce(address(this));
        address predictedRep = vm.computeCreateAddress(address(this), nonce + 2);
        address predictedVault = vm.computeCreateAddress(address(this), nonce + 3);
        accountTree = new PoseidonTree(32, DEFAULT_ROOT_HISTORY, predictedRep);
        passport = new PrivatePassport(accountTree, humanityVerifier, passportVerifier);
        reputation = new PrivateReputation(
            passport,
            accountTree,
            accountVerifier,
            admitVerifier,
            claimVerifier,
            sink, // feeRecipient (the sink doubles as it here: the fee policy is zero anyway)
            0,
            0,
            0,
            0,
            operator,
            predictedVault
        );
        vault = new PrivateBondVault(
            passport, reputation, sink, operator, depositVerifier, bondVerifier, reabsorbVerifier, withdrawVerifier
        );
        assertEq(address(reputation), predictedRep, "predicted reputation drifted");
        assertEq(address(vault), predictedVault, "predicted vault drifted");

        // Register the sample account with the V1 real-proof bundle: the account tree now
        // holds the genesis leaf0 the prepare proofs witness against.
        passport.register(proofHumanityBlob(), hn);
        reputation.register(proofAccountBlob(), hn, leaf0);

        // Fund the depositor: the deposit pulls from the caller, so the caller holds and
        // approves the exact amount.
        TestToken(token).mint(address(this), depositAmount);
        TestToken(token).approve(address(vault), depositAmount);

        wallet = vm.addr(WALLET_KEY);
    }

    // ---------------------------------------------------------------- proof blobs

    function proofHumanityBlob() internal view returns (bytes memory) {
        return vm.parseJsonBytes(proofHumanity, ".proof_with_public_inputs");
    }

    function proofAccountBlob() internal view returns (bytes memory) {
        return vm.parseJsonBytes(proofAccount, ".proof_with_public_inputs");
    }

    function proofPassportBlob() internal view returns (bytes memory) {
        return vm.parseJsonBytes(proofPassport, ".proof_with_public_inputs");
    }

    function proofAdmitBlob() internal view returns (bytes memory) {
        return vm.parseJsonBytes(proofAdmit, ".proof_with_public_inputs");
    }

    function proofDepositBlob() internal view returns (bytes memory) {
        return vm.parseJsonBytes(proofDeposit, ".proof_with_public_inputs");
    }

    function proofBondBlob() internal view returns (bytes memory) {
        return vm.parseJsonBytes(proofBond, ".proof_with_public_inputs");
    }

    function proofClaimBlob() internal view returns (bytes memory) {
        return vm.parseJsonBytes(proofClaim, ".proof_with_public_inputs");
    }

    function proofReabsorbBlob() internal view returns (bytes memory) {
        return vm.parseJsonBytes(proofReabsorb, ".proof_with_public_inputs");
    }

    function proofWithdrawBlob() internal view returns (bytes memory) {
        return vm.parseJsonBytes(proofWithdraw, ".proof_with_public_inputs");
    }

    // ---------------------------------------------------------------- the wallet consent

    /// @dev The wallet's EIP-712 consent over (dealId, dealSubject, module, deadline) — the
    ///      signature that pins a subject under a wallet for one prepare, over the named
    ///      module's own domain (§3.15.4 "Firma de wallet").
    function _walletSig(address module) internal view returns (bytes memory) {
        bytes32 structHash = keccak256(
            abi.encode(
                keccak256("PrivatePrepare(bytes32 dealId,bytes32 dealSubject,address module,uint256 deadline)"),
                dealId,
                dealSubject,
                module,
                deadline
            )
        );
        bytes32 domainSeparator = keccak256(
            abi.encode(
                // OZ v5.5's constant, byte for byte: capital "I" in chainId.
                keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"),
                keccak256(bytes("PluriSwap")),
                keccak256(bytes("1")),
                block.chainid,
                module
            )
        );
        bytes32 digest = keccak256(abi.encodePacked("\x19\x01", domainSeparator, structHash));
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(WALLET_KEY, digest);
        return abi.encodePacked(r, s, v);
    }

    // ---------------------------------------------------------------- the lifecycle

    /// @dev The full deal, every step real: deposit -> the three prepares (one tx) ->
    ///      admit -> reserve -> the terminal delta -> unlock -> reabsorb -> withdraw.
    function _runLifecycle() internal {
        // The value gate: the only place fresh value enters the notes world.
        vault.deposit(token, depositAmount, depositNote, proofDepositBlob());
        assertTrue(vault.bondRoot() == bondRoot0, "the deposit's root is the split's witness root");

        // The activation bundle: passport, bond split, admission — all before `admit`,
        // exactly as the relayer composes them (§3.15.4).
        passport.prepare(
            wallet, dealId, dealSubject, repRoot, deadline, proofPassportBlob(), _walletSig(address(passport))
        );
        vault.prepare(
            wallet,
            dealId,
            dealSubject,
            token,
            lockAmount,
            lockCommit,
            changeNote,
            nullBondNote,
            bondRoot0,
            deadline,
            proofBondBlob(),
            _walletSig(address(vault))
        );
        reputation.prepare(
            wallet,
            dealId,
            dealSubject,
            newLeaf,
            nullRep0,
            token,
            principal, // the deal's principal; the bond's §3.14.5 lock is exactly (principal+9)/10
            bytes32(0), // the base cap column: the lock is proven by the vault's own record
            repRoot,
            pairTag(),
            deadline,
            proofAdmitBlob(),
            _walletSig(address(reputation))
        );
        assertTrue(accountTree.root() == claimRoot, "the prepare's insert produced the claim's witness root");

        // The kernel's edges, against the real modules.
        vm.prank(operator);
        bytes32 subject = reputation.admit(wallet, _dealTag(), token, principal, address(vault));
        assertEq(subject, dealSubject, "the admitted subject");
        vm.prank(operator);
        vault.reserve(dealSubject, token, dealId, principal);
        vm.prank(operator);
        reputation.notifyTerminal(dealSubject, _cpTag(), token, principal, IReputation.Close.Peaceful);

        // The terminal delta, claimed with the real proof (§3.15.5).
        reputation.claim(dealId, dealSubject, claimNewLeaf, nullRep1, claimRoot, proofClaimBlob());
        assertTrue(reputation.claimed(dealSubject), "claimed gates the reabsorb");

        // The lock's way home: released by the kernel, merged by its owner (§3.15.6).
        vm.prank(operator);
        vault.unlock(dealSubject, token, dealId);
        vault.reabsorb(dealId, dealSubject, reabsorbNote, reabsorbNull, proofReabsorbBlob());

        // And the exit: part of the change note, to the proof's own dest (§3.15.6).
        vault.withdraw(
            token, withdrawDest, withdrawAmount, withdrawChangeNote, withdrawNull, withdrawRoot, proofWithdrawBlob()
        );
    }

    function test_lifecycle_realProofs() public {
        _runLifecycle();

        // The notes' end state: the tree holds [source note (spent by the split),
        // split's change note (spent by the withdraw), the reabsorbed lock's note (live),
        // the withdraw's change note (live)] — and the lock's nullifier is burned.
        assertEq(TestToken(token).balanceOf(withdrawDest), withdrawAmount, "dest paid");
        assertEq(
            TestToken(token).balanceOf(address(vault)), depositAmount - withdrawAmount, "the vault custodies the rest"
        );

        // The nullifiers of the spent notes are burned: replays die on them.
        assertTrue(vault.notesTree().isSpent(nullBondNote), "the split's nullifier");
        assertTrue(vault.notesTree().isSpent(withdrawNull), "the withdraw's nullifier");
        assertTrue(vault.notesTree().isSpent(reabsorbNull), "the reabsorb's nullifier");

        // The account's end state: the delta leaf in, the version nullifiers burned.
        assertTrue(accountTree.isSpent(nullRep0), "prepare burned v0");
        assertTrue(accountTree.isSpent(nullRep1), "claim burned v1");
        assertEq(accountTree.nextIndex(), 3, "leaf0, prepare leaf, delta leaf");
    }

    function test_vault_prepare_replayDiesOnTheNullifier() public {
        vault.deposit(token, depositAmount, depositNote, proofDepositBlob());
        vault.prepare(
            wallet,
            dealId,
            dealSubject,
            token,
            lockAmount,
            lockCommit,
            changeNote,
            nullBondNote,
            bondRoot0,
            deadline,
            proofBondBlob(),
            _walletSig(address(vault))
        );
        // The proof is valid forever, but the source note's nullifier is spent: the split
        // cannot be replayed — the tree rejects before it can grow.
        vm.expectRevert(PoseidonTree.NullifierUsed.selector);
        vault.prepare(
            wallet,
            dealId,
            dealSubject,
            token,
            lockAmount,
            lockCommit,
            changeNote,
            nullBondNote,
            bondRoot0,
            deadline,
            proofBondBlob(),
            _walletSig(address(vault))
        );
    }

    function test_withdraw_replayDiesOnTheNullifier() public {
        _runLifecycle();
        vm.expectRevert(PoseidonTree.NullifierUsed.selector);
        vault.withdraw(
            token, withdrawDest, withdrawAmount, withdrawChangeNote, withdrawNull, withdrawRoot, proofWithdrawBlob()
        );
    }

    function test_reabsorb_replayDiesOnTheNullifier() public {
        // The lock record is consumed by the reabsorb, so the second call dies on NoLock
        // even before the nullifier — the record's delete and the nullifier burn agree.
        _runLifecycle();
        vm.expectRevert(PrivateBondVault.NoLock.selector);
        vault.reabsorb(dealId, dealSubject, reabsorbNote, reabsorbNull, proofReabsorbBlob());
    }

    function test_claim_isOncePerSubject() public {
        _runLifecycle();
        vm.expectRevert(PrivateReputation.AlreadyClaimed.selector);
        reputation.claim(dealId, dealSubject, claimNewLeaf, nullRep1, claimRoot, proofClaimBlob());
    }

    function test_reabsorb_needsTheTerminalClaim() public {
        // §3.15.5's atomicity from the vault's side: without the delta the lock does not
        // come back, even released.
        vault.deposit(token, depositAmount, depositNote, proofDepositBlob());
        passport.prepare(
            wallet, dealId, dealSubject, repRoot, deadline, proofPassportBlob(), _walletSig(address(passport))
        );
        vault.prepare(
            wallet,
            dealId,
            dealSubject,
            token,
            lockAmount,
            lockCommit,
            changeNote,
            nullBondNote,
            bondRoot0,
            deadline,
            proofBondBlob(),
            _walletSig(address(vault))
        );
        reputation.prepare(
            wallet,
            dealId,
            dealSubject,
            newLeaf,
            nullRep0,
            token,
            100_000_000,
            bytes32(0),
            repRoot,
            pairTag(),
            deadline,
            proofAdmitBlob(),
            _walletSig(address(reputation))
        );
        vm.prank(operator);
        vault.reserve(dealSubject, token, dealId, principal);
        vm.prank(operator);
        vault.unlock(dealSubject, token, dealId);
        // Released but not claimed: the reabsorb fails closed on the gate, not the proof.
        vm.expectRevert(PrivateBondVault.ClaimRequired.selector);
        vault.reabsorb(dealId, dealSubject, reabsorbNote, reabsorbNull, proofReabsorbBlob());
    }

    function test_vault_prepare_rejectsBadWalletSignature() public {
        vault.deposit(token, depositAmount, depositNote, proofDepositBlob());
        bytes memory sig = _walletSig(address(vault));
        sig[10] = sig[10] ^ 0xff; // a broken signature cannot pin a subject under a wallet
        vm.expectRevert(PrivateBondVault.InvalidWalletSignature.selector);
        vault.prepare(
            wallet,
            dealId,
            dealSubject,
            token,
            lockAmount,
            lockCommit,
            changeNote,
            nullBondNote,
            bondRoot0,
            deadline,
            proofBondBlob(),
            sig
        );
    }

    function test_reserve_crossChecksTheLock() public {
        // §3.14.5: the reserve recomputes the lock from the kernel's principal — a split
        // proven for another lock (or another token) cannot write a record.
        vault.deposit(token, depositAmount, depositNote, proofDepositBlob());
        passport.prepare(
            wallet, dealId, dealSubject, repRoot, deadline, proofPassportBlob(), _walletSig(address(passport))
        );
        vault.prepare(
            wallet,
            dealId,
            dealSubject,
            token,
            lockAmount,
            lockCommit,
            changeNote,
            nullBondNote,
            bondRoot0,
            deadline,
            proofBondBlob(),
            _walletSig(address(vault))
        );
        vm.prank(operator);
        vm.expectRevert(PrivateBondVault.PrepareMismatch.selector);
        vault.reserve(dealSubject, token, dealId, principal + 1); // a different principal
    }

    // ---------------------------------------------------------------- adapter negatives

    function test_deposit_rejectsWrongArgs() public view {
        address wrongToken = address(uint160(uint256(keccak256("not-the-token"))));
        uint256 wrongAmount = depositAmount + 1;
        bytes32 wrongNote = bytes32(uint256(keccak256("other-note")));
        assertTrue(depositVerifier.verifyDeposit(token, depositAmount, depositNote, proofDepositBlob()));
        assertFalse(depositVerifier.verifyDeposit(wrongToken, depositAmount, depositNote, proofDepositBlob()));
        assertFalse(depositVerifier.verifyDeposit(token, wrongAmount, depositNote, proofDepositBlob()));
        assertFalse(depositVerifier.verifyDeposit(token, depositAmount, wrongNote, proofDepositBlob()));
    }

    function test_bond_rejectsWrongArgs() public view {
        bytes32 wrongSubject = bytes32(uint256(keccak256("other-subject")));
        bytes32 wrongDeal = bytes32(uint256(keccak256("other-deal")));
        address wrongToken = address(uint160(uint256(keccak256("not-the-token"))));
        uint256 wrongLock = lockAmount + 1;
        bytes32 wrongCommit = bytes32(uint256(keccak256("other-commit")));
        bytes32 wrongChange = bytes32(uint256(keccak256("other-change")));
        bytes32 wrongNull = bytes32(uint256(keccak256("other-null")));
        bytes32 wrongRoot = bytes32(uint256(keccak256("other-root")));
        assertTrue(
            bondVerifier.verifyBond(
                dealSubject, dealId, token, lockAmount, lockCommit, changeNote, nullBondNote, bondRoot0, proofBondBlob()
            )
        );
        assertFalse(
            bondVerifier.verifyBond(
                wrongSubject,
                dealId,
                token,
                lockAmount,
                lockCommit,
                changeNote,
                nullBondNote,
                bondRoot0,
                proofBondBlob()
            )
        );
        assertFalse(
            bondVerifier.verifyBond(
                dealSubject,
                wrongDeal,
                token,
                lockAmount,
                lockCommit,
                changeNote,
                nullBondNote,
                bondRoot0,
                proofBondBlob()
            )
        );
        assertFalse(
            bondVerifier.verifyBond(
                dealSubject,
                dealId,
                wrongToken,
                lockAmount,
                lockCommit,
                changeNote,
                nullBondNote,
                bondRoot0,
                proofBondBlob()
            )
        );
        assertFalse(
            bondVerifier.verifyBond(
                dealSubject, dealId, token, wrongLock, lockCommit, changeNote, nullBondNote, bondRoot0, proofBondBlob()
            )
        );
        assertFalse(
            bondVerifier.verifyBond(
                dealSubject,
                dealId,
                token,
                lockAmount,
                wrongCommit,
                changeNote,
                nullBondNote,
                bondRoot0,
                proofBondBlob()
            )
        );
        assertFalse(
            bondVerifier.verifyBond(
                dealSubject,
                dealId,
                token,
                lockAmount,
                lockCommit,
                wrongChange,
                nullBondNote,
                bondRoot0,
                proofBondBlob()
            )
        );
        assertFalse(
            bondVerifier.verifyBond(
                dealSubject, dealId, token, lockAmount, lockCommit, changeNote, wrongNull, bondRoot0, proofBondBlob()
            )
        );
        assertFalse(
            bondVerifier.verifyBond(
                dealSubject, dealId, token, lockAmount, lockCommit, changeNote, nullBondNote, wrongRoot, proofBondBlob()
            )
        );
    }

    function test_claim_rejectsWrongArgs() public view {
        bytes32 wrongDeal = bytes32(uint256(keccak256("other-deal")));
        bytes32 wrongSubject = bytes32(uint256(keccak256("other-subject")));
        bytes32 wrongLeaf = bytes32(uint256(keccak256("other-leaf")));
        bytes32 wrongNull = bytes32(uint256(keccak256("other-null")));
        address wrongToken = address(uint160(uint256(keccak256("not-the-token"))));
        uint256 wrongPrincipal = principal + 1;
        bytes32 wrongRoot = bytes32(uint256(keccak256("other-root")));
        assertTrue(
            claimVerifier.verifyClaim(
                dealId,
                dealSubject,
                claimNewLeaf,
                nullRep1,
                IReputation.Close.Peaceful,
                token,
                principal,
                claimRoot,
                pairTag(),
                claimEpoch(),
                proofClaimBlob()
            )
        );
        assertFalse(
            claimVerifier.verifyClaim(
                wrongDeal,
                dealSubject,
                claimNewLeaf,
                nullRep1,
                IReputation.Close.Peaceful,
                token,
                principal,
                claimRoot,
                pairTag(),
                claimEpoch(),
                proofClaimBlob()
            )
        );
        assertFalse(
            claimVerifier.verifyClaim(
                dealId,
                wrongSubject,
                claimNewLeaf,
                nullRep1,
                IReputation.Close.Peaceful,
                token,
                principal,
                claimRoot,
                pairTag(),
                claimEpoch(),
                proofClaimBlob()
            )
        );
        assertFalse(
            claimVerifier.verifyClaim(
                dealId,
                dealSubject,
                wrongLeaf,
                nullRep1,
                IReputation.Close.Peaceful,
                token,
                principal,
                claimRoot,
                pairTag(),
                claimEpoch(),
                proofClaimBlob()
            )
        );
        assertFalse(
            claimVerifier.verifyClaim(
                dealId,
                dealSubject,
                claimNewLeaf,
                wrongNull,
                IReputation.Close.Peaceful,
                token,
                principal,
                claimRoot,
                pairTag(),
                claimEpoch(),
                proofClaimBlob()
            )
        );
        // A different Close kind names a different delta: the proof's kind pub is Peaceful.
        assertFalse(
            claimVerifier.verifyClaim(
                dealId,
                dealSubject,
                claimNewLeaf,
                nullRep1,
                IReputation.Close.Silent,
                token,
                100_000_000,
                claimRoot,
                pairTag(),
                claimEpoch(),
                proofClaimBlob()
            )
        );
        assertFalse(
            claimVerifier.verifyClaim(
                dealId,
                dealSubject,
                claimNewLeaf,
                nullRep1,
                IReputation.Close.Peaceful,
                wrongToken,
                100_000_000,
                claimRoot,
                pairTag(),
                claimEpoch(),
                proofClaimBlob()
            )
        );
        assertFalse(
            claimVerifier.verifyClaim(
                dealId,
                dealSubject,
                claimNewLeaf,
                nullRep1,
                IReputation.Close.Peaceful,
                token,
                wrongPrincipal,
                claimRoot,
                pairTag(),
                claimEpoch(),
                proofClaimBlob()
            )
        );
        assertFalse(
            claimVerifier.verifyClaim(
                dealId,
                dealSubject,
                claimNewLeaf,
                nullRep1,
                IReputation.Close.Peaceful,
                token,
                100_000_000,
                wrongRoot,
                pairTag(),
                claimEpoch(),
                proofClaimBlob()
            )
        );
    }

    function test_reabsorb_rejectsWrongArgs() public view {
        bytes32 wrongDeal = bytes32(uint256(keccak256("other-deal")));
        bytes32 wrongSubject = bytes32(uint256(keccak256("other-subject")));
        address wrongToken = address(uint160(uint256(keccak256("not-the-token"))));
        uint256 wrongAmount = lockAmount + 1;
        bytes32 wrongCommit = bytes32(uint256(keccak256("other-commit")));
        bytes32 wrongNote = bytes32(uint256(keccak256("other-note")));
        bytes32 wrongNull = bytes32(uint256(keccak256("other-null")));
        assertTrue(
            reabsorbVerifier.verifyReabsorb(
                dealId, dealSubject, token, lockAmount, lockCommit, reabsorbNote, reabsorbNull, proofReabsorbBlob()
            )
        );
        assertFalse(
            reabsorbVerifier.verifyReabsorb(
                wrongDeal, dealSubject, token, lockAmount, lockCommit, reabsorbNote, reabsorbNull, proofReabsorbBlob()
            )
        );
        assertFalse(
            reabsorbVerifier.verifyReabsorb(
                dealId, wrongSubject, token, lockAmount, lockCommit, reabsorbNote, reabsorbNull, proofReabsorbBlob()
            )
        );
        assertFalse(
            reabsorbVerifier.verifyReabsorb(
                dealId, dealSubject, wrongToken, lockAmount, lockCommit, reabsorbNote, reabsorbNull, proofReabsorbBlob()
            )
        );
        assertFalse(
            reabsorbVerifier.verifyReabsorb(
                dealId, dealSubject, token, wrongAmount, lockCommit, reabsorbNote, reabsorbNull, proofReabsorbBlob()
            )
        );
        assertFalse(
            reabsorbVerifier.verifyReabsorb(
                dealId, dealSubject, token, lockAmount, wrongCommit, reabsorbNote, reabsorbNull, proofReabsorbBlob()
            )
        );
        assertFalse(
            reabsorbVerifier.verifyReabsorb(
                dealId, dealSubject, token, lockAmount, lockCommit, wrongNote, reabsorbNull, proofReabsorbBlob()
            )
        );
        assertFalse(
            reabsorbVerifier.verifyReabsorb(
                dealId, dealSubject, token, lockAmount, lockCommit, reabsorbNote, wrongNull, proofReabsorbBlob()
            )
        );
    }

    function test_withdraw_rejectsWrongArgs() public view {
        address wrongToken = address(uint160(uint256(keccak256("not-the-token"))));
        address wrongDest = address(uint160(uint256(keccak256("not-the-dest"))));
        uint256 wrongAmount = withdrawAmount + 1;
        bytes32 wrongChange = bytes32(uint256(keccak256("other-change")));
        bytes32 wrongNull = bytes32(uint256(keccak256("other-null")));
        bytes32 wrongRoot = bytes32(uint256(keccak256("other-root")));
        assertTrue(
            withdrawVerifier.verifyWithdraw(
                token, withdrawDest, withdrawAmount, withdrawChangeNote, withdrawNull, withdrawRoot, proofWithdrawBlob()
            )
        );
        assertFalse(
            withdrawVerifier.verifyWithdraw(
                wrongToken,
                withdrawDest,
                withdrawAmount,
                withdrawChangeNote,
                withdrawNull,
                withdrawRoot,
                proofWithdrawBlob()
            )
        );
        // The dest is bound IN the proof: another dest is another withdraw, unverifiable.
        assertFalse(
            withdrawVerifier.verifyWithdraw(
                token, wrongDest, withdrawAmount, withdrawChangeNote, withdrawNull, withdrawRoot, proofWithdrawBlob()
            )
        );
        assertFalse(
            withdrawVerifier.verifyWithdraw(
                token, withdrawDest, wrongAmount, withdrawChangeNote, withdrawNull, withdrawRoot, proofWithdrawBlob()
            )
        );
        assertFalse(
            withdrawVerifier.verifyWithdraw(
                token, withdrawDest, withdrawAmount, wrongChange, withdrawNull, withdrawRoot, proofWithdrawBlob()
            )
        );
        assertFalse(
            withdrawVerifier.verifyWithdraw(
                token, withdrawDest, withdrawAmount, withdrawChangeNote, wrongNull, withdrawRoot, proofWithdrawBlob()
            )
        );
        assertFalse(
            withdrawVerifier.verifyWithdraw(
                token, withdrawDest, withdrawAmount, withdrawChangeNote, withdrawNull, wrongRoot, proofWithdrawBlob()
            )
        );
    }

    function test_adapters_rejectTamperedProofs() public view {
        bytes memory blob = proofDepositBlob();
        blob[42] = blob[42] ^ 0xff;
        assertFalse(depositVerifier.verifyDeposit(token, depositAmount, depositNote, blob));

        blob = proofBondBlob();
        blob[42] = blob[42] ^ 0xff;
        assertFalse(
            bondVerifier.verifyBond(
                dealSubject, dealId, token, lockAmount, lockCommit, changeNote, nullBondNote, bondRoot0, blob
            )
        );

        blob = proofClaimBlob();
        blob[42] = blob[42] ^ 0xff;
        assertFalse(
            claimVerifier.verifyClaim(
                dealId,
                dealSubject,
                claimNewLeaf,
                nullRep1,
                IReputation.Close.Peaceful,
                token,
                100_000_000,
                claimRoot,
                pairTag(),
                claimEpoch(),
                blob
            )
        );

        blob = proofReabsorbBlob();
        blob[42] = blob[42] ^ 0xff;
        assertFalse(
            reabsorbVerifier.verifyReabsorb(
                dealId, dealSubject, token, lockAmount, lockCommit, reabsorbNote, reabsorbNull, blob
            )
        );

        blob = proofWithdrawBlob();
        blob[42] = blob[42] ^ 0xff;
        assertFalse(
            withdrawVerifier.verifyWithdraw(
                token, withdrawDest, withdrawAmount, withdrawChangeNote, withdrawNull, withdrawRoot, blob
            )
        );
    }

    function test_adapters_rejectMalformedBlobs() public view {
        // Short blobs and truncated public-input sections read as false, never revert-shaped.
        assertFalse(depositVerifier.verifyDeposit(token, depositAmount, depositNote, hex"0011"));
        assertFalse(
            bondVerifier.verifyBond(
                dealSubject, dealId, token, lockAmount, lockCommit, changeNote, nullBondNote, bondRoot0, hex"0011"
            )
        );
        assertFalse(
            claimVerifier.verifyClaim(
                dealId,
                dealSubject,
                claimNewLeaf,
                nullRep1,
                IReputation.Close.Peaceful,
                token,
                100_000_000,
                claimRoot,
                pairTag(),
                claimEpoch(),
                hex"0011"
            )
        );
        assertFalse(
            reabsorbVerifier.verifyReabsorb(
                dealId, dealSubject, token, lockAmount, lockCommit, reabsorbNote, reabsorbNull, hex"0011"
            )
        );
        assertFalse(
            withdrawVerifier.verifyWithdraw(
                token, withdrawDest, withdrawAmount, withdrawChangeNote, withdrawNull, withdrawRoot, hex"0011"
            )
        );
        assertFalse(
            withdrawVerifier.verifyWithdraw(
                token,
                withdrawDest,
                withdrawAmount,
                withdrawChangeNote,
                withdrawNull,
                withdrawRoot,
                _truncate(proofWithdrawBlob(), 64)
            )
        );
    }

    function test_adapters_rejectCrossCircuitProofs() public view {
        // Every blob into every foreign adapter: the pub sections split differently and
        // the statements are not each other's. One representative per direction suffices
        // for the shape (the pub counts are 2, 3, 3, 7, 8, 8, 8, 6, 3 across the nine).
        assertFalse(depositVerifier.verifyDeposit(token, depositAmount, depositNote, proofHumanityBlob()));
        assertFalse(
            bondVerifier.verifyBond(
                dealSubject,
                dealId,
                token,
                lockAmount,
                lockCommit,
                changeNote,
                nullBondNote,
                bondRoot0,
                proofAdmitBlob()
            )
        );
        assertFalse(
            claimVerifier.verifyClaim(
                dealId,
                dealSubject,
                claimNewLeaf,
                nullRep1,
                IReputation.Close.Peaceful,
                token,
                100_000_000,
                claimRoot,
                pairTag(),
                claimEpoch(),
                proofBondBlob()
            )
        );
        assertFalse(
            reabsorbVerifier.verifyReabsorb(
                dealId, dealSubject, token, lockAmount, lockCommit, reabsorbNote, reabsorbNull, proofWithdrawBlob()
            )
        );
        assertFalse(
            withdrawVerifier.verifyWithdraw(
                token, withdrawDest, withdrawAmount, withdrawChangeNote, withdrawNull, withdrawRoot, proofDepositBlob()
            )
        );
        assertFalse(depositVerifier.verifyDeposit(token, depositAmount, depositNote, proofClaimBlob()));
    }

    // ---------------------------------------------------------------- gas of the real verifies

    function test_verify_gas() public {
        // Read every input BEFORE the window: `pairTag()`/`claimEpoch()` parse vectors.json through a
        // cheatcode, and a cheatcode inside the measurement is the measurement.
        bytes memory depositBlob = proofDepositBlob();
        bytes memory bondBlob = proofBondBlob();
        bytes memory claimBlob = proofClaimBlob();
        bytes memory reabsorbBlob = proofReabsorbBlob();
        bytes memory withdrawBlob = proofWithdrawBlob();
        bytes32 tag = pairTag();
        uint256 epoch = claimEpoch();

        uint256 before = gasleft();
        depositVerifier.verifyDeposit(token, depositAmount, depositNote, depositBlob);
        emit log_named_uint("verifyDeposit gas", before - gasleft());

        before = gasleft();
        bondVerifier.verifyBond(
            dealSubject, dealId, token, lockAmount, lockCommit, changeNote, nullBondNote, bondRoot0, bondBlob
        );
        emit log_named_uint("verifyBond gas", before - gasleft());

        before = gasleft();
        claimVerifier.verifyClaim(
            dealId,
            dealSubject,
            claimNewLeaf,
            nullRep1,
            IReputation.Close.Peaceful,
            token,
            principal,
            claimRoot,
            tag,
            epoch,
            claimBlob
        );
        emit log_named_uint("verifyClaim gas", before - gasleft());

        before = gasleft();
        reabsorbVerifier.verifyReabsorb(
            dealId, dealSubject, token, lockAmount, lockCommit, reabsorbNote, reabsorbNull, reabsorbBlob
        );
        emit log_named_uint("verifyReabsorb gas", before - gasleft());

        before = gasleft();
        withdrawVerifier.verifyWithdraw(
            token, withdrawDest, withdrawAmount, withdrawChangeNote, withdrawNull, withdrawRoot, withdrawBlob
        );
        emit log_named_uint("verifyWithdraw gas", before - gasleft());
    }

    /// What a private deal actually costs, in the two currencies that matter on a rollup: L2 gas and
    /// the bytes that have to reach L1. `EVALUACION.md` LHF-5 said the number was missing; it was
    /// worse than missing, it was wrong — every published per-verify figure (1.7–2.1M) had been
    /// measured with a file-reading cheatcode inside the gas window, which is ~1.1M of forge, not of
    /// the EVM. Measured clean, an UltraHonk verify is ~0.67–0.75M.
    ///
    /// A two-sided private activation carries SIX proofs (two passports, two admits, two bonds) plus
    /// the kernel's own work, all in one atomic tx (§3.15.4). The verification half is measured here;
    /// the calldata half is the proofs themselves, and on Arbitrum that is the part that reaches L1.
    function test_privateDeal_costModel() public {
        uint256 passportBytes = vm.parseJsonBytes(vm.readFile("test/fixtures/proofs/prepare_passport.json"), ".proof_with_public_inputs").length;
        uint256 admitBytes = vm.parseJsonBytes(vm.readFile("test/fixtures/proofs/prepare_admit.json"), ".proof_with_public_inputs").length;
        uint256 bondBytes = proofBondBlob().length;
        uint256 bundleBytes = 2 * passportBytes + 2 * admitBytes + 2 * bondBytes;

        emit log_named_uint("one passport proof, bytes", passportBytes);
        emit log_named_uint("one admit proof, bytes", admitBytes);
        emit log_named_uint("one bond proof, bytes", bondBytes);
        emit log_named_uint("six-proof bundle, bytes", bundleBytes);
        // The claim is a separate transaction, later: the terminal delta is not part of activation.
        emit log_named_uint("one claim proof, bytes", proofClaimBlob().length);

        // A proof is high-entropy, so a rollup's compression barely touches it: this is very close to
        // what a bundle costs in L1 data, whatever the posting mechanism prices it at.
        assertLt(bundleBytes, 60_000, "a bundle should stay well under a blob");
    }

    /// @dev Solidity cannot slice memory bytes; the truncated-blob test needs a copy.
    function _truncate(bytes memory b, uint256 n) internal pure returns (bytes memory) {
        bytes memory out = new bytes(n);
        for (uint256 i = 0; i < n; i++) {
            out[i] = b[i];
        }
        return out;
    }
}
