// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// Generated by tools/generate_full_math_vectors.py. Do not edit manually.
library FullMathVectors {
    struct Vector {
        string name;
        uint256 a;
        uint256 b;
        uint256 denominator;
        uint256 productHigh;
        uint256 productLow;
        uint256 remainder;
        uint256 expectedFloor;
        uint256 expectedCeil;
    }

    function highWordBorrowCases() internal pure returns (Vector[] memory vectors) {
        vectors = new Vector[](6);
        vectors[0] = Vector({
            name: "required_regression",
            a: 77194726158210796949047323339125271902179989777093709359638389338608753093291,
            b: 3,
            denominator: 10000,
            productHigh: 2,
            productLow: 1,
            remainder: 9873,
            expectedFloor: 23158417847463239084714197001737581570653996933128112807891516801582625927,
            expectedCeil: 23158417847463239084714197001737581570653996933128112807891516801582625928
        });
        vectors[1] = Vector({
            name: "two_times_bps",
            a: 57896044618658097711785492504343953926634992332820282019728792003956564819969,
            b: 2,
            denominator: 10000,
            productHigh: 1,
            productLow: 2,
            remainder: 9938,
            expectedFloor: 11579208923731619542357098500868790785326998466564056403945758400791312963,
            expectedCeil: 11579208923731619542357098500868790785326998466564056403945758400791312964
        });
        vectors[2] = Vector({
            name: "three_times_97",
            a: 38597363079105398474523661669562635951089994888546854679819194669304376546653,
            b: 3,
            denominator: 97,
            productHigh: 1,
            productLow: 23,
            remainder: 84,
            expectedFloor: 1193732878735218509521350360914308328384226646037531588035645195957867315875,
            expectedCeil: 1193732878735218509521350360914308328384226646037531588035645195957867315876
        });
        vectors[3] = Vector({
            name: "five_times_1009",
            a: 23158417847463239084714197001737581570653996933128112807891516801582625927988,
            b: 5,
            denominator: 1009,
            productHigh: 1,
            productLow: 4,
            remainder: 997,
            expectedFloor: 114759255933910996455471739354497430974499489262280043646637843417158701327,
            expectedCeil: 114759255933910996455471739354497430974499489262280043646637843417158701328
        });
        vectors[4] = Vector({
            name: "seven_times_65537",
            a: 16541727033902313631938712144098272550467140666520080577065369143987589948563,
            b: 7,
            denominator: 65537,
            productHigh: 1,
            productLow: 5,
            remainder: 6,
            expectedFloor: 1766820105243087041267848467410591083712559083657179364930612997358944255,
            expectedCeil: 1766820105243087041267848467410591083712559083657179364930612997358944256
        });
        vectors[5] = Vector({
            name: "high_word_three",
            a: 57896044618658097711785492504343953926634992332820282019728792003956564819969,
            b: 6,
            denominator: 10000,
            productHigh: 3,
            productLow: 6,
            remainder: 9814,
            expectedFloor: 34737626771194858627071295502606372355980995399692169211837275202373938891,
            expectedCeil: 34737626771194858627071295502606372355980995399692169211837275202373938892
        });
    }
}
