// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// Generated by tools/generate_hash_vectors.py. Do not edit manually.
library HashVectors {
    bytes32 internal constant fundingSpecTypehash =
        0xc4dc59e57894c46b5576f308c0c62fa58b836c20451b7495060eb8bbfba8ec7b;
    bytes32 internal constant fundingAuthTypehash =
        0xaf46198f1e3576a44192850ccda569421491aa8f5949aafab534fb773643ee81;
    bytes32 internal constant resolutionTypehash =
        0xa70d4925a9686a75dac10f51f0b2c029722d600185fe0538351c76de4c076f61;
    bytes32 internal constant terminalTypehash =
        0x3c21ec4b9625acf80303f064237a295ac9c1d0b021a87e6bc77fd9e81e13211b;
    bytes32 internal constant intentTypehash =
        0xc23217b69228ed1e870c5ee11b3fd999f8d4d88be09731bff3b08a7908fafa22;
    bytes32 internal constant evidenceTypehash =
        0x002a64667eed9947bef8b2ddac6afb235d8607d9d37c4f40a9c6c7cabcff2193;
    bytes32 internal constant intentSchemaId =
        0x83c4f731a73b0f36ac8d05bdedd33bd0132ca5c1e5b6039e0bc09a9adb9d2bad;
    bytes32 internal constant evidenceSchemaId =
        0x9ec689aefbbe89d14804a2526072bd906ea78fde8c30238c5377062daedae46b;
    bytes32 internal constant fundingSpecHash =
        0xc81d0dabe2cb903cd1f16f0bd4d813c124b284c87d62092fca797647729ea847;
    bytes32 internal constant fundingAuthHash =
        0x19bd46b9e0d5dbe0ee104786b6cc3f0ac834c9848310bbcbc6bcf604501712af;
    bytes32 internal constant resolutionHash =
        0x8b015012625349736684804c16c32da240f14ec349218ee100f1bb8d253cd189;
    bytes32 internal constant terminalHash =
        0xaf199cdd01a5d33a912c4730ffb8e5fc1dfcfe9adfb4e901f81773a34f808227;
    bytes32 internal constant intentHash =
        0x160e6677dacd3bca74fb82392f0151f0dfec7b59508ecec26a7234ef2461b4cb;
    bytes32 internal constant evidenceHash =
        0x9318556266d774d5dcc58c88f6d3136ef0979e4b47fea7ee848dfa9789df0d0c;
}
