// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {PoseidonT2} from "poseidon-solidity/PoseidonT2.sol";
import {PoseidonT3} from "poseidon-solidity/PoseidonT3.sol";

/// @title PrivacyCommitments
/// @notice The canonical commitments of the private layer (PLURISWAP.md §3.15.3, as amended
///         by the canonical-encoding decision) — the Solidity twin of the JS twin
///         (circuits/js/lib/commitments.ts) and the Noir crate
///         (circuits/crates/pluri_commitments). Parity is pinned by test/fixtures/vectors.json,
///         generated by `bun circuits:vectors` from the JS twin; all three must agree byte for byte.
/// @dev Every bytes32 input is interpreted mod p (the BN254 scalar): poseidon-solidity's field
///      arithmetic (addmod/mulmod) reduces internally, so raw keccak-derived IDs hash to the
///      same digest as their reduced form — the rule the circuits prove and the vectors pin.
///      Multi-field commitments chain PoseidonT3 in the pinned left fold of the amendment:
///      h0 = f0, hi = PoseidonT3(h(i-1), fi). Nullifier tags are pinned field constants.
///      On-chain the protocol never recomputes commitments — they arrive inside proofs — so
///      this library is the reference twin (tests, adapters); the commitment values are law.
library PrivacyCommitments {
    uint256 internal constant TAG_REP = 1;
    uint256 internal constant TAG_BOND = 2;
    uint256 internal constant TAG_HANDLE = 3;

    /// @dev PoseidonT2 — one input, capacity 0. The width of `S = Poseidon(sk_id)`.
    function poseidonT2(bytes32 x) internal pure returns (bytes32) {
        return bytes32(PoseidonT2.hash([uint256(x)]));
    }

    /// @dev PoseidonT3 — two inputs, capacity 0. Tree nodes, `hn`, `dealSubject`, the chain primitive.
    function poseidonT3(bytes32 a, bytes32 b) internal pure returns (bytes32) {
        return bytes32(PoseidonT3.hash([uint256(a), uint256(b)]));
    }

    /// @dev The pinned left fold: h0 = f0, hi = PoseidonT3(h(i-1), fi), in the field order of the spec.
    function chain(bytes32[] memory fields) internal pure returns (bytes32) {
        uint256 h = uint256(fields[0]);
        for (uint256 i = 1; i < fields.length; i++) {
            h = PoseidonT3.hash([h, uint256(fields[i])]);
        }
        return bytes32(h);
    }

    /// @dev `S = Poseidon(sk_id)` — the account; lives inside leafRep, never on-chain in the clear.
    function accountCommitment(bytes32 skId) internal pure returns (bytes32) {
        return poseidonT2(skId);
    }

    /// @dev `hn = Poseidon(anchor, registryId)` — the humanity nullifier; anchor is the Passport-live address.
    function hn(bytes32 anchor, bytes32 registryId) internal pure returns (bytes32) {
        return poseidonT3(anchor, registryId);
    }

    /// @dev `dealSubject = Poseidon(sk_id, dealId)` — the per-deal pseudonym; all the kernel ever sees.
    function dealSubject(bytes32 skId, bytes32 dealId) internal pure returns (bytes32) {
        return poseidonT3(skId, dealId);
    }

    /// @dev `nullRep = Poseidon(sk_id, "rep", version)` — one use per account version.
    function nullRep(bytes32 skId, uint256 version) internal pure returns (bytes32) {
        bytes32[] memory f = new bytes32[](3);
        f[0] = skId;
        f[1] = bytes32(TAG_REP);
        f[2] = bytes32(version);
        return chain(f);
    }

    /// @dev `nullBond = Poseidon(sk_id, "bond", noteSalt)` — one use per spent note.
    function nullBond(bytes32 skId, bytes32 noteSalt) internal pure returns (bytes32) {
        bytes32[] memory f = new bytes32[](3);
        f[0] = skId;
        f[1] = bytes32(TAG_BOND);
        f[2] = noteSalt;
        return chain(f);
    }

    /// @dev `handleCommit = Poseidon(sk_id, "handle", handleSalt)` — the rotable market pseudonym.
    function handleCommit(bytes32 skId, bytes32 handleSalt) internal pure returns (bytes32) {
        bytes32[] memory f = new bytes32[](3);
        f[0] = skId;
        f[1] = bytes32(TAG_HANDLE);
        f[2] = handleSalt;
        return chain(f);
    }

    /// @dev `noteBond = Poseidon(sk_id, token, amount, salt)` — the token-specific vault note (F3).
    function noteBond(bytes32 skId, bytes32 token, uint256 amount, bytes32 salt) internal pure returns (bytes32) {
        bytes32[] memory f = new bytes32[](4);
        f[0] = skId;
        f[1] = token;
        f[2] = bytes32(amount);
        f[3] = salt;
        return chain(f);
    }

    /// @dev `lockCommit = Poseidon(sk_id, dealId, lockAmount, salt)` — the earmark a reserve proves
    ///      openable. The fold's first step is exactly `dealSubject`: the lock binds to the deal.
    function lockCommit(bytes32 skId, bytes32 dealId, uint256 lockAmount, bytes32 salt)
        internal
        pure
        returns (bytes32)
    {
        bytes32[] memory f = new bytes32[](4);
        f[0] = skId;
        f[1] = dealId;
        f[2] = bytes32(lockAmount);
        f[3] = salt;
        return chain(f);
    }

    /// @dev `leafRep = Poseidon(S, count, volume, penalty, inFlight, token, salt, version)` — the account leaf.
    function leafRep(
        bytes32 s,
        uint256 count,
        uint256 volume,
        uint256 penalty,
        uint256 inFlight,
        bytes32 token,
        bytes32 salt,
        uint256 version
    ) internal pure returns (bytes32) {
        bytes32[] memory f = new bytes32[](8);
        f[0] = s;
        f[1] = bytes32(count);
        f[2] = bytes32(volume);
        f[3] = bytes32(penalty);
        f[4] = bytes32(inFlight);
        f[5] = token;
        f[6] = salt;
        f[7] = bytes32(version);
        return chain(f);
    }
}
