// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Poseidon} from "./Poseidon.sol";

/// @title PrivacyCommitments
/// @notice The canonical commitments of the private layer (PLURISWAP.md §3.15.3, as amended
///         by the canonical-encoding decision) — the Solidity twin of the JS twin
///         (circuits/js/lib/commitments.ts) and the Noir crate
///         (circuits/crates/pluri_commitments). Parity is pinned by test/fixtures/vectors.json,
///         generated by `bun circuits:vectors` from the JS twin; all three must agree byte for byte.
/// @dev Every bytes32 input is interpreted mod p (the BN254 scalar): poseidon-solidity's field
///      arithmetic (addmod/mulmod) reduces internally, so raw keccak-derived IDs hash to the
///      same digest as their reduced form — the rule the circuits prove and the vectors pin.
///      Multi-field commitments chain PoseidonT3 in the pinned left fold of the amendment:
///      h0 = f0, hi = PoseidonT3(h(i-1), fi). Nullifier tags are pinned field constants.
///      Hashing runs through the pinned poseidon-solidity singleton (`Poseidon`, PLURISWAP.md §5.1),
///      called by address and never linked, which is why every builder here is `view` and not `pure`.
///      On-chain the protocol never recomputes commitments — they arrive inside proofs — so
///      this library is the reference twin (tests, adapters); the commitment values are law.
library PrivacyCommitments {
    uint256 internal constant TAG_REP = 1;
    uint256 internal constant TAG_BOND = 2;
    uint256 internal constant TAG_HANDLE = 3;
    uint256 internal constant TAG_LEAF = 4;
    uint256 internal constant TAG_NOTE = 5;
    uint256 internal constant TAG_LOCK = 6;
    uint256 internal constant TAG_PAIR = 7;
    /// @dev The BN254 scalar field: `pairId` mixes its two inputs with field arithmetic, so the sum
    ///      and the product have to reduce exactly as they do in the circuit.
    uint256 internal constant BN254_P = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    uint256 internal constant TAG_CP = 8;

    /// @dev PoseidonT2 — one input, capacity 0. The width of `S = Poseidon(sk_id)`.
    function poseidonT2(bytes32 x) internal view returns (bytes32) {
        return bytes32(Poseidon.t2(uint256(x)));
    }

    /// @dev PoseidonT3 — two inputs, capacity 0. Tree nodes, `hn`, `dealSubject`, the chain primitive.
    function poseidonT3(bytes32 a, bytes32 b) internal view returns (bytes32) {
        return bytes32(Poseidon.t3(uint256(a), uint256(b)));
    }

    /// @dev The pinned left fold: h0 = f0, hi = PoseidonT3(h(i-1), fi), in the field order of the spec.
    function chain(bytes32[] memory fields) internal view returns (bytes32) {
        uint256 h = uint256(fields[0]);
        for (uint256 i = 1; i < fields.length; i++) {
            h = Poseidon.t3(h, uint256(fields[i]));
        }
        return bytes32(h);
    }

    /// @dev `S = Poseidon(sk_id)` — the account; lives inside leafRep, never on-chain in the clear.
    function accountCommitment(bytes32 skId) internal view returns (bytes32) {
        return poseidonT2(skId);
    }

    /// @dev `hn = Poseidon(anchor, registryId)` — the humanity nullifier; anchor is the Passport-live address.
    function hn(bytes32 anchor, bytes32 registryId) internal view returns (bytes32) {
        return poseidonT3(anchor, registryId);
    }

    /// @dev `dealSubject = Poseidon(sk_id, dealId)` — the per-deal pseudonym; all the kernel ever sees.
    function dealSubject(bytes32 skId, bytes32 dealId) internal view returns (bytes32) {
        return poseidonT3(skId, dealId);
    }

    /// @dev `nullRep = Poseidon(sk_id, "rep", version)` — one use per account version.
    function nullRep(bytes32 skId, uint256 version) internal view returns (bytes32) {
        bytes32[] memory f = new bytes32[](3);
        f[0] = skId;
        f[1] = bytes32(TAG_REP);
        f[2] = bytes32(version);
        return chain(f);
    }

    /// @dev `leafSalt = Poseidon(sk_id, "leaf", version)` — the account leaf's salt, DERIVED.
    ///      It used to be whatever the client picked, which made an account unrecoverable from its
    ///      secret: rebuilding your leaf means reproducing its salt, and the salt only lived in the
    ///      client's local state. The circuits enforce this derivation now, so `sk_id` alone is
    ///      enough to recover an account. The handle salt stays free: rotating it is the feature.
    function leafSalt(bytes32 skId, uint256 version) internal view returns (bytes32) {
        bytes32[] memory f = new bytes32[](3);
        f[0] = skId;
        f[1] = bytes32(TAG_LEAF);
        f[2] = bytes32(version);
        return chain(f);
    }

    /// @dev `noteSalt = Poseidon(sk_id, "note", seed)` — a vault note's salt, DERIVED, for the same
    ///      reason the account leaf's is, and with more at stake: a note holds TOKENS and its salt is
    ///      what spends it. Two seed families, one rule — a note's salt derives from whatever it came
    ///      from: a deposit's seed is a small per-account index (bound under 2^32 in-circuit), every
    ///      other note is change and its seed is the nullifier of the note or lock it came out of,
    ///      which the spending transaction publishes.
    function noteSalt(bytes32 skId, bytes32 seed) internal view returns (bytes32) {
        bytes32[] memory f = new bytes32[](3);
        f[0] = skId;
        f[1] = bytes32(TAG_NOTE);
        f[2] = seed;
        return chain(f);
    }

    /// @dev `lockSalt = Poseidon(sk_id, "lock", dealId)` — the earmark's salt, DERIVED from its deal.
    ///      One lock per deal per subject, so the deal id is the only index it needs.
    function lockSalt(bytes32 skId, bytes32 dealId) internal view returns (bytes32) {
        bytes32[] memory f = new bytes32[](3);
        f[0] = skId;
        f[1] = bytes32(TAG_LOCK);
        f[2] = dealId;
        return chain(f);
    }

    /// @dev `nullBond = Poseidon(sk_id, "bond", noteSalt)` — one use per spent note.
    function nullBond(bytes32 skId, bytes32 noteSalt) internal view returns (bytes32) {
        bytes32[] memory f = new bytes32[](3);
        f[0] = skId;
        f[1] = bytes32(TAG_BOND);
        f[2] = noteSalt;
        return chain(f);
    }

    /// @dev `handleCommit = Poseidon(sk_id, "handle", handleSalt)` — the rotable market pseudonym.
    function handleCommit(bytes32 skId, bytes32 handleSalt) internal view returns (bytes32) {
        bytes32[] memory f = new bytes32[](3);
        f[0] = skId;
        f[1] = bytes32(TAG_HANDLE);
        f[2] = handleSalt;
        return chain(f);
    }

    /// @dev `noteBond = Poseidon(sk_id, token, amount, salt)` — the token-specific vault note (F3).
    function noteBond(bytes32 skId, bytes32 token, uint256 amount, bytes32 salt) internal view returns (bytes32) {
        bytes32[] memory f = new bytes32[](4);
        f[0] = skId;
        f[1] = token;
        f[2] = bytes32(amount);
        f[3] = salt;
        return chain(f);
    }

    /// @dev `lockCommit = Poseidon(sk_id, dealId, lockAmount, salt)` — the earmark a reserve proves
    ///      openable. The fold's first step is exactly `dealSubject`: the lock binds to the deal.
    function lockCommit(bytes32 skId, bytes32 dealId, uint256 lockAmount, bytes32 salt)
        internal
        view
        returns (bytes32)
    {
        bytes32[] memory f = new bytes32[](4);
        f[0] = skId;
        f[1] = dealId;
        f[2] = bytes32(lockAmount);
        f[3] = salt;
        return chain(f);
    }

    /// @dev `leafRep = Poseidon(S, count, volume, penalty, inFlight, token, salt, version)` — the account leaf.
    function leafRep(
        bytes32 s,
        uint256 count,
        uint256 volume,
        uint256 penalty,
        uint256 inFlight,
        bytes32 token,
        bytes32 salt,
        uint256 version,
        /// @dev The §3.14.7 anti-farming state (2026-09-23): the root of this account's own
        ///      counterparty tree — who has already been credited to it — and the rate window it is
        ///      in. Added while nothing was deployed: a leaf field cannot be added afterwards without
        ///      leaving every existing leaf unprovable.
        bytes32 cpRoot,
        uint256 epoch,
        uint256 epochCredits
    ) internal view returns (bytes32) {
        bytes32[] memory f = new bytes32[](11);
        f[0] = s;
        f[1] = bytes32(count);
        f[2] = bytes32(volume);
        f[3] = bytes32(penalty);
        f[4] = bytes32(inFlight);
        f[5] = token;
        f[6] = salt;
        f[7] = bytes32(version);
        f[8] = cpRoot;
        f[9] = bytes32(epoch);
        f[10] = bytes32(epochCredits);
        return chain(f);
    }

    /// @dev `pairId = Poseidon("pair", S_a + S_b, S_a · S_b)` — the name two accounts share, computed
    ///      commutatively without ordering them. Each side proves it with its own `S` bound to its own
    ///      leaf, so the two proofs agree only if each used the other's real value.
    function pairId(bytes32 sA, bytes32 sB) internal view returns (bytes32) {
        uint256 a = uint256(sA);
        uint256 b = uint256(sB);
        bytes32[] memory f = new bytes32[](3);
        f[0] = bytes32(TAG_PAIR);
        f[1] = bytes32(addmod(a, b, BN254_P));
        f[2] = bytes32(mulmod(a, b, BN254_P));
        return chain(f);
    }

    /// @dev `pairTag = Poseidon(pairId, dealId)` — blinded by the deal, so it proves agreement WITHIN
    ///      an activation and says nothing across deals.
    function pairTag(bytes32 sA, bytes32 sB, bytes32 dealId) internal view returns (bytes32) {
        return poseidonT3(pairId(sA, sB), dealId);
    }
}
