/**
 * Poseidon singleton fixture generator.
 *
 * PluriSwap does NOT compile poseidon-solidity into this tree: `PoseidonT3`'s runtime under our
 * compiler settings is 29,315 B, over the EIP-170 wall, so a locally linked library is a contract
 * that cannot be deployed on any chain that enforces the limit. What the protocol uses instead is
 * the upstream DEPLOYMENT: the pinned submodule ships a pre-signed CREATE2 blob whose runtime does
 * fit, deployed through Arachnid's deterministic-deployment-proxy at a fixed address on every EVM.
 *
 * This generator lifts that blob out of the submodule into `test/fixtures/poseidon.json` and
 * proves, offline, that `CREATE2(proxy, salt, initcode)` is exactly the address the contracts pin.
 * Same shape as `circuits:vectors`: the fixture is committed, CI regenerates it and requires
 * `git diff --exit-code`, so the pinned addresses can never drift away from the pinned bytecode.
 */
import { keccak256 } from "js-sha3";
import { readFileSync, writeFileSync } from "node:fs";

/** Arachnid's deterministic-deployment-proxy — the CREATE2 factory upstream deploys through. */
const DEPLOYER = "0x4e59b44847b379578588920cA78FbF26c0B4956C";
/** Its 69-byte runtime: `salt || initcode` in calldata, CREATE2 out. Pinned so tests can etch it. */
const DEPLOYER_RUNTIME =
  "0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf3";

const SINGLETONS = ["PoseidonT2", "PoseidonT3"] as const;
const FIXTURE = "test/fixtures/poseidon.json";

function create2(deployer: string, salt: string, initcode: string): string {
  const pre = Buffer.from(
    "ff" + deployer.slice(2).toLowerCase() + salt.slice(2) + keccak256(Buffer.from(initcode.slice(2), "hex")),
    "hex",
  );
  return "0x" + keccak256(pre).slice(24);
}

const singletons: Record<string, { address: string; salt: string; initcode: string }> = {};
for (const name of SINGLETONS) {
  const source = readFileSync(`lib/poseidon-solidity/deploy/${name}.js`, "utf8");
  const address = /address\s*:\s*'(0x[0-9a-fA-F]{40})'/.exec(source)?.[1];
  const data = /data\s*:\s*'(0x[0-9a-fA-F]+)'/.exec(source)?.[1];
  if (!address || !data) throw new Error(`${name}: could not read address/data from the submodule`);

  // The proxy takes `salt || initcode` as raw calldata; the first 32 bytes are the salt.
  const salt = "0x" + data.slice(2, 66);
  const initcode = "0x" + data.slice(66);

  const derived = create2(DEPLOYER, salt, initcode);
  if (derived.toLowerCase() !== address.toLowerCase()) {
    throw new Error(`${name}: CREATE2 derives ${derived}, submodule declares ${address}`);
  }
  singletons[name] = { address, salt, initcode };
  console.log(`${name}: ${address} (initcode ${(initcode.length - 2) / 2} B) — CREATE2 verified`);
}

writeFileSync(
  FIXTURE,
  JSON.stringify(
    {
      _: "GENERATED by `bun poseidon:fixture` from lib/poseidon-solidity (pinned submodule). Do not edit.",
      deployer: DEPLOYER,
      deployerRuntime: DEPLOYER_RUNTIME,
      singletons,
    },
    null,
    2,
  ) + "\n",
);
console.log(`wrote ${FIXTURE}`);
