export type PathNeed = "core" | "packages" | "labVerbs" | "zkArb" | "pool" | "ramp";

export type PathTemplate = {
  id: string;
  recintoHint: string;
  fiatDuration: string;
  releaseDuration: string;
  disputeDuration: string;
  arbitrationDuration: string;
  p2p: boolean;
  needs: PathNeed[];
  sequence: string;
  assertion: string;
};

/** LAB_UI.md §7. CASE-CORE-11 never clones zeros into releaseDuration. */
export const PATHS: PathTemplate[] = [
  {
    id: "PATH-CORE-ONLY",
    recintoHint: "sepolia.json / 31337.json",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["core"],
    sequence: "packageIds=[] activate P2P 6-arg dummy CA",
    assertion: "kinds==0, subjects==0",
  },
  {
    id: "CASE-CORE-01-P2P",
    recintoHint: "core + su testToken",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["core"],
    sequence: "HA+PA, dummy CA, activate",
    assertion: "FUNDED",
  },
  {
    id: "CASE-CORE-01-CTRL",
    recintoHint: "core",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: false,
    needs: ["core"],
    sequence: "HA+PA+CA hashed",
    assertion: "FUNDED, 3 used",
  },
  {
    id: "CASE-CORE-02",
    recintoHint: "core",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["core"],
    sequence: "markFiat",
    assertion: "FIAT_SENT",
  },
  {
    id: "CASE-CORE-03",
    recintoHint: "core",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["core"],
    sequence: "cancelByProvider",
    assertion: "CANCELLED, holderAmt=principal",
  },
  {
    id: "CASE-CORE-04",
    recintoHint: "core",
    fiatDuration: "0",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["core"],
    sequence: "timeoutFiat due inmediato",
    assertion: "CANCELLED",
  },
  {
    id: "CASE-CORE-05",
    recintoHint: "core",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["core"],
    sequence: "composer mutualCancel FUNDED",
    assertion: "CANCELLED",
  },
  {
    id: "CASE-CORE-06",
    recintoHint: "core",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["core"],
    sequence: "markFiat → release",
    assertion: "RELEASED; Core-only providerAmt=principal",
  },
  {
    id: "CASE-CORE-07",
    recintoHint: "core",
    fiatDuration: "3600",
    releaseDuration: "0",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["core"],
    sequence: "markFiat → claim due inmediato",
    assertion: "RELEASED (no status CLAIMED); sin completion fee",
  },
  {
    id: "CASE-CORE-08",
    recintoHint: "core",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["core"],
    sequence: "composer mutualCancel FIAT_SENT",
    assertion: "CANCELLED",
  },
  {
    id: "CASE-CORE-09",
    recintoHint: "core",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["core"],
    sequence: "composer split bps=2500",
    assertion: "RESOLVED_SPLIT",
  },
  {
    id: "CASE-CORE-10",
    recintoHint: "core",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["core"],
    sequence: "composer coSignedRelease",
    assertion: "RELEASED",
  },
  {
    id: "CASE-CORE-11",
    recintoHint: "core",
    fiatDuration: "3600",
    releaseDuration: "100",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["core"],
    sequence: "openDisputed strictly-before",
    assertion: "DISPUTED. releaseDuration no es 0",
  },
  {
    id: "CASE-CORE-12",
    recintoHint: "core",
    fiatDuration: "3600",
    releaseDuration: "100",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["core"],
    sequence: "composer mutualCancel DISPUTED",
    assertion: "CANCELLED",
  },
  {
    id: "CASE-CORE-13",
    recintoHint: "core",
    fiatDuration: "3600",
    releaseDuration: "100",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["core"],
    sequence: "composer coSigned DISPUTED",
    assertion: "RELEASED",
  },
  {
    id: "CASE-CORE-14",
    recintoHint: "core",
    fiatDuration: "3600",
    releaseDuration: "100",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["core"],
    sequence: "composer split bps=4000",
    assertion: "RESOLVED_SPLIT",
  },
  {
    id: "CASE-CORE-15",
    recintoHint: "core",
    fiatDuration: "3600",
    releaseDuration: "100",
    disputeDuration: "0",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["core"],
    sequence: "openDisputed luego forceStalemate due",
    assertion: "STALEMATE 50/50",
  },
  {
    id: "CASE-CORE-16",
    recintoHint: "core",
    fiatDuration: "3600",
    releaseDuration: "100",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["core"],
    sequence: "release/claim en DISPUTED",
    assertion: "matriz WrongStatus",
  },
  {
    id: "CASE-CORE-17",
    recintoHint: "core",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["core"],
    sequence: "verbo de estado en terminal",
    assertion: "WrongStatus",
  },
  {
    id: "PATH-TRIO",
    recintoHint: "packages + su testToken",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["packages", "labVerbs"],
    sequence: "LAB setHuman ×2, vault.deposit, slots P+R+B, activate, markFiat, release",
    assertion: "activationFee; completionFee en release; Peaceful; bonds unlock",
  },
  {
    id: "PATH-ZK-PROOF",
    recintoHint: "packages",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["packages", "labVerbs", "zkArb"],
    sequence: "slot ZK, FUNDED, LAB abi.encode(dealId,nullifier), verifyProof",
    assertion: "RELEASED; markFiat EdgeOff",
  },
  {
    id: "PATH-ZK-TIMEOUT",
    recintoHint: "packages",
    fiatDuration: "0",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["packages", "zkArb"],
    sequence: "ZK, timeoutFiat",
    assertion: "CANCELLED, sin fee ZK",
  },
  {
    id: "PATH-ARB-MOCK",
    recintoHint: "packages",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: String(86_400),
    p2p: true,
    needs: ["packages", "labVerbs", "zkArb"],
    sequence: "court=ArbitrationMock; approve court; msg.value=0; markFiat; openCourt; LAB submitRuling; readRuling",
    assertion: "arbitrationDuration=1 days, no mezclar con disputeDuration",
  },
  {
    id: "PATH-KLEROS",
    recintoHint: "kleros-packages",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: String(7 * 86_400),
    p2p: true,
    needs: ["packages", "zkArb"],
    sequence: "P2P dummy CA; kernel() vs Recinto; msg.value == arbitrationCost; markFiat; openCourt",
    assertion: "ARBITRATION_ACTIVE; no submitRuling",
  },
  {
    id: "PATH-POOL-HOLDER",
    recintoHint: "pool.json cuyo escrow == Recinto",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: false,
    needs: ["pool"],
    sequence: "deposit; authorize(ha); holder=pool; holderSig=\"\"; CA hashed; PA; markFiat; release; reconcile",
    assertion: "Holder=pool; dummy CA revierte",
  },
  {
    id: "PATH-RAMP-TAXI",
    recintoHint: "ramp.json (USDC, no TestToken)",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["ramp"],
    sequence: "deal Core con USDC ya en Holder, release, IRamp.send",
    assertion: "sin compose",
  },
  {
    id: "PATH-NEGATIVE-ZK-ARB",
    recintoHint: "packages",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["packages"],
    sequence: "slots ZK+ARB, ambos ids en packageIds",
    assertion: "IncompatiblePackages; un id → UnknownPackage primero",
  },
  {
    id: "PATH-NEGATIVE-UNSORTED",
    recintoHint: "core",
    fiatDuration: "3600",
    releaseDuration: "1800",
    disputeDuration: "7200",
    arbitrationDuration: "0",
    p2p: true,
    needs: ["packages"],
    sequence: "packageIds no canónicos",
    assertion: "Terms.UnsortedPackageIds antes de TermsMismatch",
  },
];

export function pathById(id: string): PathTemplate | undefined {
  return PATHS.find((p) => p.id === id);
}
