#!/usr/bin/env python3
"""Generate independent high-word-borrow vectors for FullMath tests."""

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path


UINT256_MODULUS = 1 << 256
UINT256_MAX = UINT256_MODULUS - 1
ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "test" / "vectors" / "FullMathVectors.sol"


@dataclass(frozen=True)
class Case:
    name: str
    a: int
    b: int
    denominator: int


@dataclass(frozen=True)
class Vector:
    case: Case
    product_high: int
    product_low: int
    remainder: int
    expected_floor: int
    expected_ceil: int


CASES = (
    Case(
        "required_regression",
        77194726158210796949047323339125271902179989777093709359638389338608753093291,
        3,
        10_000,
    ),
    Case("two_times_bps", UINT256_MODULUS // 2 + 1, 2, 10_000),
    Case("three_times_97", (UINT256_MODULUS + 2) // 3 + 7, 3, 97),
    Case("five_times_1009", (UINT256_MODULUS + 4) // 5, 5, 1_009),
    Case("seven_times_65537", (UINT256_MODULUS + 5) // 7, 7, 65_537),
    Case("high_word_three", UINT256_MODULUS // 2 + 1, 6, 10_000),
)


def calculate_vector(case: Case) -> Vector:
    for value_name, value in (
        ("a", case.a),
        ("b", case.b),
        ("denominator", case.denominator),
    ):
        if not 0 <= value <= UINT256_MAX:
            raise ValueError(f"{case.name}: {value_name} is outside uint256")

    product = case.a * case.b
    product_high, product_low = divmod(product, UINT256_MODULUS)
    expected_floor, remainder = divmod(product, case.denominator)
    expected_ceil = expected_floor + (remainder != 0)

    if product_high == 0:
        raise ValueError(f"{case.name}: product does not use the high word")
    if case.denominator <= product_high:
        raise ValueError(f"{case.name}: quotient does not fit uint256")
    if remainder <= product_low:
        raise ValueError(f"{case.name}: remainder subtraction does not require a borrow")
    if expected_floor > UINT256_MAX or expected_ceil > UINT256_MAX:
        raise ValueError(f"{case.name}: expected result does not fit uint256")

    return Vector(
        case=case,
        product_high=product_high,
        product_low=product_low,
        remainder=remainder,
        expected_floor=expected_floor,
        expected_ceil=expected_ceil,
    )


def render(vectors: tuple[Vector, ...]) -> str:
    lines = [
        "// SPDX-License-Identifier: MIT",
        "pragma solidity ^0.8.24;",
        "",
        "// Generated by tools/generate_full_math_vectors.py. Do not edit manually.",
        "library FullMathVectors {",
        "    struct Vector {",
        "        string name;",
        "        uint256 a;",
        "        uint256 b;",
        "        uint256 denominator;",
        "        uint256 productHigh;",
        "        uint256 productLow;",
        "        uint256 remainder;",
        "        uint256 expectedFloor;",
        "        uint256 expectedCeil;",
        "    }",
        "",
        "    function highWordBorrowCases() internal pure returns (Vector[] memory vectors) {",
        f"        vectors = new Vector[]({len(vectors)});",
    ]

    for index, vector in enumerate(vectors):
        case = vector.case
        lines.extend(
            [
                f"        vectors[{index}] = Vector({{",
                f'            name: "{case.name}",',
                f"            a: {case.a},",
                f"            b: {case.b},",
                f"            denominator: {case.denominator},",
                f"            productHigh: {vector.product_high},",
                f"            productLow: {vector.product_low},",
                f"            remainder: {vector.remainder},",
                f"            expectedFloor: {vector.expected_floor},",
                f"            expectedCeil: {vector.expected_ceil}",
                "        });",
            ]
        )

    lines.extend(["    }", "}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed Solidity fixture is not up to date",
    )
    args = parser.parse_args()

    rendered = render(tuple(calculate_vector(case) for case in CASES))
    relative_output = OUTPUT.relative_to(ROOT)

    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            print(f"{relative_output} is not up to date", file=sys.stderr)
            return 1
        print(f"{relative_output} is up to date")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered)
    print(f"Wrote {relative_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
